# Catégories du Bac Éclair : (packs, libellé lu par le copilote, difficulté, lettres exclues).
# Une lettre n'est autorisée que si un non-spécialiste trouve au moins 2 mots en 10 secondes
# (CONTENT_GUIDE §4.4). Les lettres rares (K Q W X Y Z) ne sortent que si l'option est activée ;
# on les exclut ici quand elles sont impossibles pour la catégorie.
G, SC, BE, POP, SP, HS, GEO, FOOD = 'general', 'scotland', 'belgium', 'pop', 'sport', 'history-science', 'geo-travel', 'food'
RARE_HARD = ['K', 'Q', 'W', 'X', 'Y', 'Z']
ITEMS = [
 # ── Classiques ──────────────────────────────────────────
 ([G, HS, SC, GEO, FOOD], 'Un animal', 1, []),
 ([G, GEO, SP, FOOD, HS], 'Un pays', 1, ['W', 'X']),
 ([G, SC, SP], 'Un prénom', 1, []),
 ([G, HS], 'Un métier', 1, ['W', 'X', 'Y']),
 ([G], 'Un objet', 1, []),
 ([G, FOOD], 'Un fruit ou un légume', 1, ['J', 'U', 'W', 'X', 'Z']),
 ([G, GEO, SP, FOOD], 'Une ville de France', 1, ['K', 'X', 'Z']),
 ([G, SP], 'Un sport', 1, ['I', 'U', 'X', 'Z']),
 ([G, SC, SP], 'Une couleur', 2, ['U', 'Q', 'W', 'X', 'Y', 'Z']),
 ([G, POP, SC], 'Un instrument de musique', 2, ['E', 'I', 'J', 'N', 'Q', 'W', 'Y', 'Z']),
 ([G, HS, SP], 'Une partie du corps', 1, ['K', 'Q', 'W', 'X', 'Z']),
 ([G, SC, SP], 'Un vêtement', 1, ['I', 'O', 'Q', 'W', 'X', 'Y', 'Z']),
 ([G, HS, SC], 'Un oiseau', 2, ['J', 'U', 'Q', 'W', 'X', 'Y', 'Z']),
 ([G, FOOD, BE, GEO], 'Un plat', 1, ['I', 'U', 'Q', 'W', 'X', 'Y', 'Z']),
 ([FOOD, BE, G], 'Un dessert', 2, ['H', 'J', 'U', 'Q', 'W', 'X', 'Y', 'Z']),
 ([G, FOOD, SC, SP], 'Une boisson', 1, ['U', 'X', 'Y', 'Z']),
 ([G, HS, SC, FOOD, GEO], 'Un arbre', 2, ['U', 'V', 'Q', 'W', 'X', 'Z']),
 ([G, SC, HS], 'Une fleur', 1, ['U', 'Q', 'W', 'X', 'Y', 'K']),
 ([G, BE, SP, FOOD], 'Une marque', 1, []),
 ([G, GEO, BE, SP, HS], 'Une ville du monde', 1, []),
 ([G, GEO, HS, SP], 'Une capitale', 2, ['F', 'G', 'U', 'X']),
 ([G, GEO, SP], 'Un moyen de transport', 2, ['E', 'G', 'I', 'O', 'U', 'W', 'X']),
 ([G, FOOD], 'Quelque chose qu’on trouve dans une cuisine', 1, ['I', 'J', 'U', 'K', 'Q', 'W', 'X', 'Y', 'Z']),
 ([G, GEO, SC, SP], 'Quelque chose qu’on met dans une valise', 1, RARE_HARD),
 ([G, GEO], 'Quelque chose qu’on trouve à la plage', 1, ['I', 'J', 'U', 'K', 'Q', 'W', 'X', 'Y', 'Z']),
 ([G], 'Quelque chose qu’on trouve dans une salle de bain', 1, ['I', 'J', 'N', 'O', 'U', 'K', 'Q', 'W', 'X', 'Y', 'Z']),
 ([G, GEO, SP], 'Quelque chose qu’on trouve dans une voiture', 2, ['I', 'N', 'O', 'U', 'Q', 'W', 'X', 'Y', 'Z']),
 ([G], 'Quelque chose qu’on trouve dans un bureau', 1, ['H', 'J', 'U', 'Q', 'W', 'X', 'Y', 'Z']),
 ([G, FOOD], 'Quelque chose qu’on trouve dans un jardin', 1, ['Q', 'W', 'X', 'Y', 'Z']),
 ([G, SC, FOOD, GEO], 'Quelque chose qu’on trouve dans une forêt', 1, ['Q', 'W', 'X', 'Y', 'Z']),
 ([G, FOOD], 'Quelque chose de rond', 2, ['Q', 'W', 'X', 'Y', 'Z']),
 ([G, SC], 'Quelque chose qui fait du bruit', 2, RARE_HARD),
 ([G, SC, FOOD], 'Quelque chose de froid', 2, ['Q', 'W', 'X', 'Y', 'Z']),
 ([G, GEO], 'Quelque chose qui vole', 2, ['I', 'N', 'U', 'Q', 'W', 'X', 'Y']),
 ([G], 'Quelque chose qu’on peut ouvrir', 2, ['Q', 'W', 'X', 'Y', 'Z']),
 ([G, BE], 'Un mot en lien avec Noël', 2, ['I', 'U', 'Q', 'W', 'X', 'Y', 'Z']),
 ([G], 'Un mot en lien avec l’école', 1, ['Q', 'W', 'X', 'Y', 'Z']),
 ([G, FOOD], 'Un cadeau', 1, ['Q', 'W', 'X', 'Y', 'Z']),
 ([G, HS], 'Un outil', 2, ['I', 'J', 'N', 'O', 'U', 'Q', 'W', 'X', 'Y', 'Z']),
 ([G], 'Un verbe', 1, []),
 ([G], 'Un adjectif', 1, []),
 ([G, SC, BE, SP], 'Un nom de famille', 1, []),
 ([G, FOOD], 'Une chose qu’on trouve au supermarché', 1, []),
 # ── Culture pop ──────────────────────────────────────────
 ([POP, G], 'Un personnage de dessin animé', 1, ['Q', 'X']),
 ([POP, G, SC, BE], 'Un chanteur ou une chanteuse', 1, ['Q', 'X']),
 ([POP, G, BE], 'Un film', 1, []),
 ([POP], 'Une série télé', 2, []),
 ([POP, G], 'Un personnage de Disney', 1, ['U', 'Q', 'X', 'Y', 'W']),
 ([POP], 'Un personnage de film', 2, ['Q', 'X', 'Y']),
 ([POP, G], 'Un jeu de société ou un jeu de cartes', 2, ['F', 'H', 'I', 'N', 'V', 'Q', 'W', 'X', 'Y', 'Z']),
 ([POP], 'Un jeu vidéo', 2, []),
 ([POP, G, SC], 'Un acteur ou une actrice', 1, ['Q', 'X']),
 ([POP, BE], 'Un personnage de bande dessinée', 2, ['E', 'U', 'Q', 'W', 'X', 'Y']),
 ([POP, SC], 'Un groupe de musique', 2, []),
 ([POP, BE], 'Une chanson', 2, []),
 ([POP, G], 'Un dessin animé', 1, []),
 ([POP, HS], 'Un livre ou un roman', 2, []),
 ([POP, HS, SC], 'Un écrivain ou une écrivaine', 2, ['U', 'X']),
 ([POP, HS, BE], 'Un peintre ou une peintre', 3, ['E', 'I', 'J', 'N', 'U', 'Q', 'X', 'Y', 'Z']),
 ([POP, SC], 'Un personnage de légende ou de conte', 2, ['E', 'I', 'U', 'V', 'Q', 'W', 'X', 'Y', 'Z']),
 ([POP, SC], 'Un monstre ou une créature fantastique', 2, ['I', 'J', 'R', 'U', 'Q', 'W', 'X', 'Y']),
 ([POP], 'Un personnage de Harry Potter', 3, ['E', 'I', 'O', 'U', 'Q', 'W', 'X', 'Y', 'Z']),
 ([POP, HS], 'Un personnage de la mythologie', 3, ['Q', 'W', 'X', 'Y']),
 ([POP], 'Une émission de télé', 2, ['X']),
 ([POP, BE], 'Un acteur ou une actrice français ou belge', 2, ['U', 'Q', 'W', 'X']),
 ([POP, BE], 'Un humoriste', 3, ['I', 'U', 'Q', 'W', 'X', 'Y']),
 ([POP], 'Un mot lié au cinéma', 2, ['Q', 'W', 'X', 'Y', 'Z']),
 ([POP, SC], 'Un mot lié à la musique', 2, ['Q', 'W', 'X', 'Y', 'Z']),
 # ── Sport ────────────────────────────────────────────────
 ([SP, G], 'Un sportif ou une sportive célèbre', 1, ['Q', 'X']),
 ([SP, BE], 'Un footballeur ou une footballeuse', 2, ['U', 'Q', 'X']),
 ([SP, BE, GEO], 'Un club de football', 2, ['Q', 'X']),
 ([SP], 'Un mot lié au football', 2, ['Q', 'W', 'X', 'Y', 'Z']),
 ([SP], 'Un joueur ou une joueuse de tennis', 3, ['I', 'U', 'Q', 'X']),
 ([SP, BE], 'Un coureur ou une coureuse cycliste', 3, ['U', 'Q', 'W', 'X', 'Y']),
 ([SP], 'Un accessoire de sport', 2, ['I', 'N', 'O', 'U', 'Q', 'W', 'X', 'Y', 'Z']),
 ([SP, G], 'Un mot lié au sport', 1, ['Q', 'W', 'X', 'Y', 'Z']),
 ([SP], 'Un sportif français ou une sportive française', 2, ['U', 'Q', 'W', 'X', 'Y']),
 ([SP, SC], 'Un sport qui se pratique dehors', 2, ['I', 'J', 'U', 'Q', 'W', 'X', 'Z']),
 # ── Géographie & voyages ────────────────────────────────
 ([GEO, HS], 'Un monument', 3, ['D', 'F', 'H', 'J', 'U', 'Q', 'X', 'Y', 'Z']),
 ([GEO, BE, SP], 'Un pays d’Europe', 2, ['J', 'O', 'K', 'Q', 'W', 'X', 'Y', 'Z']),
 ([GEO, BE, HS], 'Un fleuve ou une rivière', 3, ['B', 'F', 'H', 'J', 'U', 'K', 'Q', 'W', 'X', 'Y', 'Z']),
 ([GEO, SC], 'Une île', 2, ['U', 'K', 'Q', 'W', 'X', 'Y']),
 ([GEO, SC, HS], 'Une ville du Royaume-Uni', 3, ['J', 'U', 'V', 'K', 'Q', 'X', 'Z']),
 ([GEO, BE, HS, SP, FOOD], 'Une ville d’Europe', 1, []),
 ([GEO, HS], 'Un pays d’Amérique', 3, ['F', 'I', 'L', 'O', 'K', 'W', 'X', 'Y', 'Z']),
 ([GEO, HS, BE], 'Une langue', 2, ['X']),
 ([GEO, SC, SP], 'Un mot lié à la mer', 2, ['Q', 'W', 'X', 'Y', 'Z']),
 ([GEO, SC, HS], 'Un mot lié à la météo', 2, ['J', 'U', 'Q', 'W', 'X', 'Y', 'Z']),
 ([GEO, SC], 'Un paysage ou un élément de la nature', 2, ['Q', 'W', 'X', 'Y', 'Z']),
 ([GEO, SC, SP], 'Un mot lié à la montagne', 2, ['Q', 'W', 'X', 'Y', 'Z']),
 ([GEO], 'Une chose qu’on fait en vacances', 1, ['Q', 'W', 'X', 'Y', 'Z']),
 ([GEO, SC], 'Un animal sauvage', 1, []),
 # ── Gastronomie ──────────────────────────────────────────
 ([FOOD, BE], 'Un fromage', 2, ['I', 'J', 'U', 'K', 'Q', 'W', 'X', 'Y', 'Z']),
 ([FOOD, SC], 'Un poisson ou un fruit de mer', 2, ['I', 'J', 'N', 'U', 'Q', 'W', 'X', 'Y', 'Z']),
 ([FOOD], 'Une épice ou une herbe aromatique', 3, ['D', 'H', 'I', 'J', 'U', 'K', 'Q', 'W', 'X', 'Y']),
 ([FOOD, BE], 'Une friandise ou une sucrerie', 2, ['E', 'I', 'J', 'O', 'U', 'Q', 'W', 'X', 'Y']),
 ([FOOD, G], 'Quelque chose de sucré', 1, ['Q', 'W', 'X', 'Y']),
 ([FOOD, G, BE], 'Un ingrédient de cuisine', 1, ['W', 'X']),
 ([FOOD], 'Une spécialité régionale française', 3, ['E', 'I', 'J', 'O', 'U', 'W', 'X', 'Y', 'Z']),
 ([FOOD], 'Un légume', 2, ['D', 'I', 'J', 'U', 'V', 'Q', 'W', 'X', 'Y']),
 ([FOOD, SC], 'Un mot lié à la cuisine', 1, ['Q', 'W', 'X', 'Y', 'Z']),
 ([FOOD, GEO], 'Un plat étranger', 2, ['E', 'I', 'O', 'U', 'Q', 'W', 'X', 'Y']),
 # ── Belgique ─────────────────────────────────────────────
 ([BE, FOOD], 'Une bière belge', 3, ['E', 'I', 'N', 'U', 'K', 'Q', 'X', 'Y']),
 ([BE, GEO], 'Une ville ou une commune belge', 2, ['J', 'Q', 'X']),
 ([BE, FOOD], 'Une spécialité belge', 3, ['D', 'E', 'I', 'J', 'N', 'O', 'U', 'K', 'Q', 'X', 'Y', 'Z']),
 ([BE, POP], 'Un personnage de Tintin', 3, ['E', 'F', 'G', 'I', 'J', 'O', 'P', 'U', 'V', 'K', 'Q', 'W', 'X', 'Y']),
 ([BE, POP], 'Un chanteur ou une chanteuse francophone', 2, ['U', 'Q', 'W', 'X']),
 # ── Écosse ───────────────────────────────────────────────
 ([SC, POP], 'Un mot anglais', 2, []),
 ([SC, POP], 'Un prénom anglais ou écossais', 2, ['U', 'Q', 'X']),
 ([SC], 'Un tissu ou une matière', 3, ['E', 'H', 'I', 'O', 'U', 'Q', 'W', 'X', 'Y', 'Z']),
 ([SC, HS], 'Quelque chose qu’on trouve dans un château', 2, ['Q', 'X', 'Y', 'Z']),
 # ── Histoire & sciences ──────────────────────────────────
 ([HS, G], 'Un inventeur ou une scientifique', 2, ['I', 'O', 'U', 'Q', 'X', 'Y', 'Z']),
 ([HS, G], 'Un personnage historique', 1, ['U', 'Q', 'X']),
 ([HS], 'Une invention', 2, ['J', 'N', 'U', 'Q', 'W', 'X', 'Y', 'Z']),
 ([HS], 'Un mot lié à l’espace', 2, ['Q', 'W', 'X', 'Y', 'Z']),
 ([HS, G, SP], 'Un mot lié à la santé ou à la médecine', 2, ['Q', 'W', 'X', 'Y', 'Z']),
 ([HS], 'Un mot lié à la nature ou à l’environnement', 2, ['Q', 'W', 'X', 'Y', 'Z']),
 ([HS, BE], 'Un mot lié à l’histoire', 2, ['Q', 'W', 'X', 'Y', 'Z']),
 ([HS, G], 'Un mot lié à la science', 2, ['Q', 'W', 'X', 'Y', 'Z']),
 ([FOOD, G], 'Un mot lié au repas ou à la table', 1, ['Q', 'W', 'X', 'Y', 'Z']),
]
