# Questions d'Estimation. Format :
# (packs, question, unité, réponse, difficulté, anecdote, année de référence ou None)
G, SC, BE, POP, SP, HS, GEO, FOOD = 'general', 'scotland', 'belgium', 'pop', 'sport', 'history-science', 'geo-travel', 'food'
ITEMS = [
 # ── Corps humain & vivant ───────────────────────────────
 ([HS, G], "Combien d'os compte le squelette d'un adulte ?", 'os', 206, 1, "Un nouveau-né en a bien davantage : beaucoup fusionnent en grandissant.", None),
 ([HS, G], 'Combien de dents compte la denture complète d’un adulte ?', 'dents', 32, 1, "Dont les quatre dents de sagesse, qui ne sortent pas chez tout le monde.", None),
 ([HS], 'Combien de litres de sang circulent dans le corps d’un adulte ?', 'litres', 5, 2, "Le cœur fait circuler tout ce sang en à peu près une minute.", None),
 ([HS], 'Combien pèse un cerveau humain adulte ?', 'kilos', 1.4, 2, "Il consomme environ 20 % de l'énergie du corps.", None),
 ([HS], 'Combien de chromosomes possède une cellule humaine ?', 'chromosomes', 46, 2, "Ils vont par paires : la moitié vient de la mère, l'autre du père.", None),
 ([HS, G], 'Combien de vertèbres compte le cou d’une girafe ?', 'vertèbres', 7, 3, "Autant que dans le cou humain : chacune mesure simplement jusqu'à 25 centimètres.", None),
 ([HS], 'Combien de mois dure la gestation d’un éléphant ?', 'mois', 22, 2, "C'est la plus longue gestation de tous les mammifères terrestres.", None),
 ([HS], 'Combien de mètres peut mesurer une baleine bleue ?', 'mètres', 30, 2, "C'est le plus grand animal ayant jamais existé, dinosaures compris.", None),
 ([HS], 'Combien d’yeux possède une abeille ?', 'yeux', 5, 3, "Deux gros yeux composés et trois petits yeux simples sur le dessus de la tête.", None),
 ([HS, G], 'Combien de cœurs possède une pieuvre ?', 'cœurs', 3, 2, "Son sang est bleu, car il transporte l'oxygène grâce au cuivre.", None),
 ([HS], 'À combien de kilomètres par heure peut courir un guépard ?', 'km/h', 110, 2, "Il ne tient cette vitesse que sur quelques centaines de mètres.", None),
 ([HS], 'Combien de pattes possède une araignée ?', 'pattes', 8, 1, "Les araignées ne sont pas des insectes, qui n'en ont que six.", None),
 ([HS], 'Combien de battements par minute fait le cœur d’un adulte au repos ?', 'battements', 70, 1, "Celui d'un colibri peut dépasser 1 000 battements par minute.", None),
 ([HS], 'Combien de kilomètres de vaisseaux sanguins compte un corps humain adulte ?', 'km', 100000, 3, "Mis bout à bout, ils feraient plus de deux fois le tour de la Terre.", None),
 # ── Espace & Terre ──────────────────────────────────────
 ([HS, G], 'Quelle est la distance moyenne entre la Terre et la Lune ?', 'km', 384400, 2, "La Lune s'éloigne de nous d'environ 3,8 centimètres par an.", None),
 ([HS], 'Quelle est la vitesse de la lumière ?', 'km par seconde', 300000, 2, "La lumière du Soleil met environ 8 minutes à nous parvenir.", None),
 ([HS], 'Quelle est la température à la surface du Soleil ?', '°C', 5500, 3, "En son cœur, la température dépasse 15 millions de degrés.", None),
 ([HS, G], 'Combien de planètes compte le système solaire ?', 'planètes', 8, 1, "Jupiter est si grosse que toutes les autres planètes tiendraient à l'intérieur.", None),
 ([HS], 'Quel est l’âge de l’Univers ?', "milliards d'années", 13.8, 3, "On le mesure notamment grâce au rayonnement fossile, un « écho » du Big Bang.", None),
 ([HS], 'Quel est l’âge de la Terre ?', "milliards d'années", 4.5, 2, "Les plus vieilles roches connues ont environ 4 milliards d'années.", None),
 ([HS], 'Combien d’éléments compte le tableau périodique ?', 'éléments', 118, 3, "Les derniers ont reçu leur nom en 2016, dont l'oganesson.", None),
 ([HS], 'À quelle température bout l’eau au sommet de l’Everest ?', '°C', 70, 3, "Plus on monte, plus l'eau bout tôt : impossible d'y cuire correctement des pâtes.", None),
 ([HS], 'Quelle est la distance moyenne entre la Terre et le Soleil ?', 'km', 150000000, 2, "C'est ce qu'on appelle une unité astronomique.", None),
 ([HS, GEO], 'Quel est le diamètre de la Terre ?', 'km', 12742, 2, "La Terre est légèrement aplatie aux pôles.", None),
 ([HS, GEO], 'Quelle est la longueur de l’équateur ?', 'km', 40075, 2, "Le mètre a d'abord été défini à partir de la longueur d'un méridien terrestre.", None),
 ([HS], 'Quelle est la vitesse du son dans l’air ?', 'mètres par seconde', 343, 3, "Comptez environ trois secondes entre l'éclair et le tonnerre par kilomètre d'orage.", None),
 ([HS], 'Combien d’astronautes ont marché sur la Lune ?', 'astronautes', 12, 2, "Tous étaient américains, entre 1969 et 1972.", None),
 ([HS], 'À quelle altitude orbite la Station spatiale internationale ?', 'km', 400, 2, "À cette hauteur, elle fait le tour de la Terre en une heure et demie.", None),
 ([HS], 'Combien de fois par jour la Station spatiale fait-elle le tour de la Terre ?', 'tours', 16, 3, "Ses astronautes voient donc 16 levers de soleil par jour.", None),
 ([HS], 'Combien de temps la lumière du Soleil met-elle pour arriver jusqu’à nous ?', 'minutes', 8.3, 2, "Si le Soleil s'éteignait, on ne s'en apercevrait qu'après ce délai.", None),
 ([HS], 'Combien de lunes compte Mars ?', 'lunes', 2, 2, "Elles s'appellent Phobos et Déimos, la peur et la terreur.", None),
 ([HS], 'Combien de jours dure une année sur Mars ?', 'jours terrestres', 687, 3, "Une journée martienne ne dure qu'environ 40 minutes de plus que la nôtre.", None),
 ([HS], 'Quelle est la profondeur de la fosse des Mariannes ?', 'mètres', 11000, 3, "Si on y posait l'Everest, son sommet resterait à plus de 2 kilomètres sous l'eau.", None),
 # ── Géographie ──────────────────────────────────────────
 ([GEO, G], 'Quelle est la hauteur de l’Everest ?', 'mètres', 8849, 2, "Cette mesure date de 2020, réalisée conjointement par la Chine et le Népal.", 2020),
 ([GEO, G], 'Quelle est la hauteur du mont Blanc ?', 'mètres', 4806, 2, "Sa hauteur varie de quelques mètres selon l'épaisseur de neige au sommet.", 2023),
 ([GEO], 'Quelle est la longueur du Nil ?', 'km', 6650, 2, "Il dispute à l'Amazone le titre de plus long fleuve du monde.", None),
 ([GEO, G], 'Quelle est la longueur de la Loire ?', 'km', 1006, 2, "C'est le plus long fleuve qui coule entièrement en France.", None),
 ([GEO], 'Quelle est la superficie de la France métropolitaine ?', 'km²', 550000, 2, "C'est le plus grand pays de l'Union européenne.", None),
 ([GEO], 'Quelle est la superficie de la Russie ?', 'km²', 17000000, 2, "Elle s'étend sur onze fuseaux horaires.", None),
 ([GEO], 'Quelle est la largeur de la Manche au pas de Calais ?', 'km', 33, 2, "Par temps clair, on voit les falaises anglaises depuis le cap Gris-Nez.", None),
 ([GEO], 'Quelle est la longueur du tunnel sous la Manche ?', 'km', 50, 2, "Dont environ 38 kilomètres sous la mer.", None),
 ([GEO], 'Combien de pays compte l’Afrique ?', 'pays', 54, 2, "Le plus grand par la superficie est l'Algérie.", 2025),
 ([GEO, G], 'Combien d’États compte les États-Unis ?', 'États', 50, 1, "Les deux derniers à les rejoindre sont l'Alaska et Hawaï, en 1959.", None),
 ([GEO], 'Quelle est la longueur de la Grande Muraille de Chine, avec toutes ses branches ?', 'km', 21000, 3, "Contrairement à une idée reçue, on ne la voit pas à l'œil nu depuis l'espace.", None),
 ([GEO], 'Quelle est la hauteur de la Burj Khalifa ?', 'mètres', 828, 2, "Depuis le sommet, on peut voir le soleil se coucher plus tard qu'au pied de la tour.", None),
 ([GEO, HS], 'Quelle était la hauteur d’origine de la pyramide de Khéops ?', 'mètres', 146, 2, "Elle a été le plus haut monument construit par l'homme pendant près de 4 000 ans.", None),
 ([GEO, G], 'Quelle est la hauteur de la statue de la Liberté, socle compris ?', 'mètres', 93, 2, "Sa tête mesure plus de 5 mètres du menton au sommet du crâne.", None),
 ([GEO, G], 'Quelle est la hauteur de la tour Eiffel, antennes comprises ?', 'mètres', 330, 1, "Elle grandit d'une quinzaine de centimètres en été, à cause de la dilatation du métal.", 2022),
 ([GEO], 'Combien de marches faut-il gravir pour monter au deuxième étage de la tour Eiffel ?', 'marches', 674, 3, "Au-delà du deuxième étage, il faut prendre l'ascenseur.", None),
 ([GEO], 'Combien de pays le Danube traverse-t-il ?', 'pays', 10, 3, "Il traverse quatre capitales, dont Vienne et Budapest.", None),
 ([GEO], 'Combien d’habitants compte l’Islande ?', 'habitants', 390000, 3, "Plus de la moitié des habitants vivent dans la région de Reykjavik.", 2025),
 ([GEO, G], 'Combien d’habitants compte la France ?', 'habitants', 68600000, 1, "La France est le deuxième pays le plus peuplé de l'Union européenne, après l'Allemagne.", 2025),
 ([GEO, G], 'Combien d’habitants compte la planète ?', 'habitants', 8200000000, 1, "La population mondiale a doublé depuis le milieu des années 1970.", 2025),
 ([GEO], 'Combien d’habitants compte la Chine ?', 'habitants', 1400000000, 1, "L'Inde l'a dépassée en 2023 pour devenir le pays le plus peuplé.", 2025),
 ([GEO], 'Combien d’habitants compte Paris, sans sa banlieue ?', 'habitants', 2100000, 2, "Paris est l'une des capitales les plus densément peuplées au monde.", 2025),
 ([GEO, G], 'Combien de pays compte l’Union européenne ?', 'pays', 27, 1, "Le Royaume-Uni l'a quittée en 2020.", 2025),
 ([GEO, HS], 'Combien de pays sont membres de l’ONU ?', 'pays', 193, 2, "Le dernier admis est le Soudan du Sud, en 2011.", 2025),
 ([GEO, G], 'Combien de départements compte la France ?', 'départements', 101, 2, "Dont cinq départements d'outre-mer.", 2025),
 ([GEO], 'Combien de communes compte la France ?', 'communes', 34900, 3, "Plus de la moitié comptent moins de 500 habitants.", 2025),
 ([GEO], 'Quelle est la longueur du canal de Panama ?', 'km', 82, 3, "Les navires y sont hissés par des écluses jusqu'à un lac en altitude.", None),
 ([GEO], 'Quelle est la longueur du Transsibérien, de Moscou à Vladivostok ?', 'km', 9300, 3, "Le voyage complet dure environ une semaine.", None),
 ([GEO], 'Quelle est la profondeur du lac Baïkal ?', 'mètres', 1640, 3, "C'est le lac le plus profond du monde, et il contient environ 20 % de l'eau douce liquide de la planète.", None),
 ([GEO], 'Combien de pays ont une frontière commune avec la France métropolitaine ?', 'pays', 8, 2, "Dont Andorre et Monaco, deux des plus petits pays d'Europe.", None),
 ([GEO], 'Quelle est la hauteur des chutes du Niagara côté canadien ?', 'mètres', 57, 3, "Les chutes reculent naturellement à cause de l'érosion de la roche.", None),
 ([GEO], 'Quelle est la superficie du Sahara ?', 'km²', 9000000, 3, "C'est le plus grand désert chaud du monde, à peu près la taille des États-Unis.", None),
 # ── Belgique ─────────────────────────────────────────────
 ([BE, GEO], 'Combien d’habitants compte la Belgique ?', 'habitants', 11800000, 1, "La Région de Bruxelles-Capitale en compte à elle seule environ 1,2 million.", 2025),
 ([BE, GEO], 'Quelle est la superficie de la Belgique ?', 'km²', 30689, 2, "On peut la traverser en voiture en moins de quatre heures.", None),
 ([BE], 'Quelle est la hauteur de l’Atomium ?', 'mètres', 102, 2, "Ses neuf sphères représentent les atomes d'un cristal de fer.", None),
 ([BE], 'Quelle est la hauteur du Manneken-Pis ?', 'centimètres', 55.5, 2, "La statue exposée est une copie : l'original est conservé à la Maison du Roi.", None),
 ([BE, G], 'Combien de langues officielles compte la Belgique ?', 'langues', 3, 1, "L'allemand est parlé par moins de 80 000 personnes, à l'est du pays.", None),
 ([BE], 'Combien de provinces compte la Belgique ?', 'provinces', 10, 2, "Cinq en Flandre et cinq en Wallonie ; Bruxelles n'appartient à aucune.", None),
 ([BE, GEO], 'Quelle est la longueur de la côte belge ?', 'km', 67, 2, "Un tram la longe presque entièrement, de La Panne à Knokke.", None),
 ([BE, GEO], 'Quelle est l’altitude du signal de Botrange, point culminant de la Belgique ?', 'mètres', 694, 3, "Une butte artificielle permet d'y atteindre symboliquement 700 mètres.", None),
 ([BE, POP], 'Combien de Schtroumpfs vivent dans le village ?', 'Schtroumpfs', 100, 3, "La Schtroumpfette n'a pas été créée par le Grand Schtroumpf, mais par Gargamel.", None),
 ([BE], 'Combien de jours la Belgique est-elle restée sans gouvernement de plein exercice en 2010-2011 ?', 'jours', 541, 3, "C'est souvent cité comme un record mondial en temps de paix.", None),
 ([BE, GEO, G], 'Combien de pays ont une frontière avec la Belgique ?', 'pays', 4, 1, "France, Pays-Bas, Allemagne et Luxembourg : la mer du Nord ferme le dernier côté.", None),
 ([BE, HS], 'Combien de marches faut-il gravir pour monter au sommet de la Butte du Lion, à Waterloo ?', 'marches', 226, 3, "La butte a été élevée à l'endroit où le prince d'Orange aurait été blessé.", None),
 ([BE, SP], 'Combien de titres du Grand Chelem Justine Henin a-t-elle remportés en simple ?', 'titres', 7, 3, "Dont quatre à Roland-Garros.", None),
 ([BE, SP], 'Combien de Tours de France Eddy Merckx a-t-il gagnés ?', 'Tours', 5, 1, "Avec 34 victoires d'étape, il a détenu le record jusqu'à ce que Mark Cavendish le dépasse en 2024.", None),
 ([BE, GEO], "Combien d'habitants compte la ville d'Anvers ?", 'habitants', 540000, 3, "Son port est le deuxième d'Europe, derrière Rotterdam.", 2025),
 ([BE], 'Combien de cloches compte le carillon du beffroi de Bruges ?', 'cloches', 47, 3, "Le carillonneur y donne encore régulièrement des concerts.", None),
 ([BE], 'Combien de marches faut-il gravir pour monter au sommet du beffroi de Bruges ?', 'marches', 366, 3, "Le beffroi, haut de 83 mètres, penche légèrement vers l'est.", None),
 ([BE, POP], "Combien de fois la Belgique a-t-elle remporté l'Eurovision ?", 'victoire', 1, 2, "Sandra Kim avait 13 ans, même si elle avait déclaré en avoir 15.", 2025),
 ([BE], 'Combien de saxophones géants décorent le pont Charles de Gaulle, à Dinant ?', 'saxophones', 28, 3, "Chacun est décoré aux couleurs d'un pays de l'Union européenne.", None),
 ([BE, SP], "Combien de titres de champion de Belgique de football compte le RSC Anderlecht ?", 'titres', 34, 3, "C'est de loin le club le plus titré du pays.", 2025),
 ([BE, GEO], 'Quelle est la superficie de la Région de Bruxelles-Capitale ?', 'km²', 161, 3, "Elle compte 19 communes.", None),
 ([BE, HS], 'Combien de rois a eu la Belgique depuis 1831 ?', 'rois', 7, 2, "L'actuel, Philippe, règne depuis 2013.", 2025),
 ([BE, SP], 'Quelle est la longueur du circuit de Spa-Francorchamps ?', 'km', 7.004, 3, "Son virage le plus célèbre, le raidillon de l'Eau Rouge, est une montée très raide.", None),
 ([BE, GEO], "Combien d'habitants compte la ville de Liège ?", 'habitants', 197000, 3, "Le 15 août, le quartier d'Outremeuse fête sa marionnette emblématique, Tchantchès.", 2025),
 ([BE, FOOD], 'Combien de fois les frites belges traditionnelles sont-elles plongées dans l’huile ?', 'fois', 2, 1, "Une première cuisson à cœur, puis une seconde, plus chaude, pour les rendre croustillantes.", None),
 # ── Écosse ───────────────────────────────────────────────
 ([SC, GEO], 'Quelle est l’altitude du Ben Nevis, le plus haut sommet du Royaume-Uni ?', 'mètres', 1345, 2, "Un observatoire météo a fonctionné en permanence à son sommet de 1883 à 1904.", None),
 ([SC, GEO], 'Quelle est la profondeur maximale du Loch Ness ?', 'mètres', 230, 3, "Il contient plus d'eau douce que tous les lacs d'Angleterre et du pays de Galles réunis.", None),
 ([SC, GEO], 'Quelle est la longueur du Loch Ness ?', 'km', 36, 2, "Le lac est étroit : à peine 2 à 3 kilomètres de large.", None),
 ([SC, GEO], "Combien d'habitants compte l'Écosse ?", 'habitants', 5500000, 2, "Glasgow est la plus grande ville, devant Édimbourg, la capitale.", 2025),
 ([SC], 'Quelle est la longueur du Forth Bridge, le pont ferroviaire rouge ?', 'km', 2.5, 3, "Le repeindre entièrement était réputé être un travail sans fin.", None),
 ([SC, FOOD], 'Combien d’années un whisky écossais doit-il vieillir au minimum ?', 'ans', 3, 2, "Il doit vieillir en fût de chêne, en Écosse, pour avoir droit à ce nom.", None),
 ([SC, FOOD], 'Quel est le degré d’alcool minimum d’un whisky écossais ?', '% vol.', 40, 2, "Beaucoup de whiskies « brut de fût » dépassent les 55 %.", None),
 ([SC, SP], 'Combien de « Munros », sommets écossais de plus de 3 000 pieds, compte-t-on ?', 'sommets', 282, 3, "Les gravir tous est un défi : ceux qui y parviennent sont appelés « compléteurs ».", 2025),
 ([SC, POP], 'Combien de bourdons, les longs tuyaux qui font la note de fond, a une cornemuse écossaise ?', 'bourdons', 3, 3, "Ils donnent une note continue sous la mélodie.", None),
 ([SC, HS], 'Quelle est la longueur du mur d’Hadrien, construit par les Romains ?', 'km', 117, 3, "Contrairement à une idée reçue, il se trouve entièrement en Angleterre.", None),
 ([SC, GEO], 'Quelle est la longueur du Royal Mile, la grande rue de la vieille ville d’Édimbourg ?', 'km', 1.8, 3, "Il est plus long qu'un mile anglais : il mesure un ancien mile écossais.", None),
 ([SC, GEO], "Combien d'habitants compte la ville de Glasgow ?", 'habitants', 630000, 3, "Son métro, ouvert en 1896, est l'un des plus anciens du monde.", 2025),
 ([SC, GEO], "Combien d'habitants compte la ville d'Édimbourg ?", 'habitants', 520000, 3, "Son château est bâti sur le cône d'un ancien volcan.", 2025),
 ([SC], 'Combien de lettres compte l’alphabet gaélique écossais traditionnel ?', 'lettres', 18, 3, "Les lettres J, K, Q, V, W, X, Y et Z n'en font pas partie.", None),
 ([SC, SP], 'Combien de titres du Grand Chelem Andy Murray a-t-il gagnés en simple ?', 'titres', 3, 2, "Il a aussi remporté deux médailles d'or olympiques en simple.", None),
 ([SC, SP], 'Combien de titres de champion du monde de snooker l’Écossais Stephen Hendry a-t-il gagnés ?', 'titres', 7, 3, "Il a remporté le premier à seulement 21 ans.", None),
 ([SC, SP, G], 'Combien de trous compte un parcours de golf classique ?', 'trous', 18, 1, "Ce standard vient du parcours de St Andrews, en Écosse.", None),
 ([SC, GEO], "Quelle est la superficie de l'Écosse ?", 'km²', 78000, 3, "Elle compte des centaines d'îles, dont une centaine sont habitées.", None),
 ([SC], 'Quelle est la hauteur de la Roue de Falkirk, l’ascenseur à bateaux ?', 'mètres', 35, 3, "Elle relie deux canaux situés à des hauteurs différentes.", None),
 ([SC], 'Quelle est la hauteur des Kelpies, les deux têtes de chevaux géantes près de Falkirk ?', 'mètres', 30, 3, "Elles rendent hommage aux chevaux de trait qui tiraient les bateaux sur les canaux.", None),
 ([SC, SP], "Combien de spectateurs peut accueillir Murrayfield, le stade de rugby d'Édimbourg ?", 'places', 67000, 3, "C'est le plus grand stade d'Écosse.", 2025),
 ([SC, GEO], "Quelle est l'altitude d'Arthur's Seat, la colline qui domine Édimbourg ?", 'mètres', 251, 3, "C'est le sommet d'un volcan éteint, en pleine ville.", None),
 ([SC, SP], 'Quelle est la longueur de la West Highland Way, le célèbre sentier de randonnée ?', 'km', 154, 3, "Il relie la banlieue de Glasgow à Fort William, au pied du Ben Nevis.", None),
 ([SC, HS], 'Combien de députés siègent au Parlement écossais ?', 'députés', 129, 3, "Le Parlement siège à Holyrood, au pied de la vieille ville d'Édimbourg.", 2025),
 ([SC, POP], 'Quelle est la hauteur du Scott Monument, à Édimbourg ?', 'mètres', 61, 3, "C'est le plus grand monument au monde dédié à un écrivain.", None),
 ([SC, HS], 'Combien de licornes figurent sur les armoiries royales d’Écosse ?', 'licornes', 2, 3, "La licorne est l'animal national de l'Écosse.", None),
 # ── Culture pop & jeux ───────────────────────────────────
 ([POP, SC], 'Combien de films officiels de James Bond sont sortis ?', 'films', 25, 2, "Sean Connery, le premier à l'incarner, était écossais.", 2025),
 ([POP], 'Combien de minutes dure le film « Titanic » ?', 'minutes', 194, 3, "Le film dure plus longtemps que le naufrage réel, qui a pris environ 2 h 40.", None),
 ([POP, G], 'Combien de saisons compte la série « Friends » ?', 'saisons', 10, 1, "Le dernier épisode a été suivi par plus de 50 millions d'Américains.", None),
 ([POP], 'Combien d’épisodes compte la série « Friends » ?', 'épisodes', 236, 3, "La série compte dix saisons.", None),
 ([POP, G], 'Combien de livres compte la saga Harry Potter ?', 'livres', 7, 1, "Au cinéma, le dernier tome a été découpé en deux films.", None),
 ([POP], 'Combien de Pokémon compte la toute première génération ?', 'Pokémon', 151, 2, "Le premier du Pokédex, n° 1, est Bulbizarre.", None),
 ([POP, G], 'Combien de cases compte une grille de Sudoku ?', 'cases', 81, 2, "Une grille bien construite n'admet qu'une seule solution.", None),
 ([POP, G], 'Combien de cases compte le plateau du Monopoly ?', 'cases', 40, 2, "Dans la version française, la rue la plus chère est la rue de la Paix.", None),
 ([POP], "Combien de petits carrés colorés compte un Rubik's Cube classique ?", 'carrés', 54, 2, "Il existe plus de 43 milliards de milliards de combinaisons.", None),
 ([POP], 'Combien de lettres compte un jeu de Scrabble français, jokers compris ?', 'lettres', 102, 3, "Les lettres K, W, X, Y et Z valent 10 points.", None),
 ([POP, G], 'Combien de pièces compte un jeu d’échecs complet ?', 'pièces', 32, 1, "Seize par joueur, dont huit pions.", None),
 ([POP], 'Combien de cases compte un damier international ?', 'cases', 100, 2, "Chaque joueur commence avec 20 pions.", None),
 ([POP], "Combien d'Oscars a remportés le film « Titanic » ?", 'Oscars', 11, 2, "Un record partagé avec « Ben-Hur » et « Le Retour du roi ».", None),
 ([POP], 'Combien de secondes dure « Bohemian Rhapsody » de Queen ?', 'secondes', 355, 3, "Sa maison de disques la trouvait trop longue pour passer à la radio.", None),
 ([POP], 'Combien de films compte la saga principale « Star Wars » ?', 'films', 9, 2, "La saga est découpée en trois trilogies.", None),
 ([POP, BE], "Combien d'albums d'Astérix sont parus ?", 'albums', 41, 3, "Depuis la mort de Goscinny en 1977, plusieurs auteurs ont pris la relève.", 2025),
 ([POP, G], 'Combien de dalmatiens dans le titre du célèbre dessin animé de Disney ?', 'dalmatiens', 101, 1, "Le film est adapté d'un roman de l'Anglaise Dodie Smith.", None),
 ([POP, G], 'Combien de cartes compte un jeu classique, sans les jokers ?', 'cartes', 52, 1, "Les quatre couleurs sont pique, cœur, carreau et trèfle.", None),
 ([POP], "Combien de cases compte le jeu de l'oie ?", 'cases', 63, 3, "Celui qui tombe sur la case 58, la tête de mort, doit recommencer au début.", None),
 ([POP], 'Combien de pions compte un jeu de Puissance 4 ?', 'pions', 42, 3, "La grille compte 7 colonnes et 6 lignes.", None),
 ([POP], 'Combien d’épisodes compte la série « Game of Thrones » ?', 'épisodes', 73, 3, "La série compte huit saisons.", None),
 ([POP], 'Combien de Grammy Awards Beyoncé a-t-elle remportés ?', 'Grammy Awards', 35, 3, "C'est l'artiste la plus récompensée de l'histoire des Grammy Awards.", 2025),
 ([POP, G], 'Combien de films compte la saga Harry Potter au cinéma ?', 'films', 8, 1, "Le dernier livre a été découpé en deux films.", None),
 ([POP], "Combien d'Oscars Walt Disney a-t-il remportés personnellement ?", 'Oscars', 22, 3, "C'est le record pour une seule personne.", None),
 ([POP], "Combien de chansons compte l'album « Thriller » de Michael Jackson ?", 'chansons', 9, 3, "Sept d'entre elles sont sorties en single.", None),
 ([POP], "Combien de fois la France a-t-elle remporté l'Eurovision ?", 'victoires', 5, 3, "La dernière victoire remonte à 1977, avec Marie Myriam.", 2025),
 ([POP], 'Combien de films principaux compte la saga « Fast and Furious » ?', 'films', 10, 3, "Vin Diesel y incarne Dominic Toretto.", 2025),
 ([POP], 'Combien de lettres compte le mot « supercalifragilisticexpialidocious » ?', 'lettres', 34, 3, "Le mot vient d'une chanson de « Mary Poppins ».", None),
 ([POP, G], 'Combien de nains accompagnent Blanche-Neige ?', 'nains', 7, 1, "Dans le film de Disney, ils s'appellent notamment Prof, Grincheux et Simplet.", None),
 # ── Sport ────────────────────────────────────────────────
 ([SP, G], 'Quelle est la distance d’un marathon ?', 'km', 42.195, 1, "Cette distance a été fixée lors des Jeux de Londres, en 1908.", None),
 ([SP], 'Quelle est la hauteur d’un but de football ?', 'mètres', 2.44, 2, "Soit 8 pieds : les dimensions viennent du système anglais.", None),
 ([SP], 'Quelle est la largeur d’un but de football ?', 'mètres', 7.32, 2, "Soit 8 yards : là encore, une mesure anglaise.", None),
 ([SP], 'Combien de joueurs figurent sur une feuille de match de rugby à XV, remplaçants compris ?', 'joueurs', 23, 3, "Quinze titulaires et huit remplaçants.", None),
 ([SP], 'À quelle hauteur est fixé un panier de basket ?', 'mètres', 3.05, 2, "Soit exactement 10 pieds, la hauteur choisie par l'inventeur du jeu.", None),
 ([SP, G], 'Quelle est la longueur d’un bassin olympique ?', 'mètres', 50, 1, "Il compte en général dix couloirs, dont huit utilisés en finale.", None),
 ([SP], "Quelle est la longueur d'un court de tennis ?", 'mètres', 23.77, 3, "Les dimensions viennent du système anglais : 78 pieds.", None),
 ([SP], "Quel est le record du monde du 100 mètres d'Usain Bolt ?", 'secondes', 9.58, 2, "Il l'a établi à Berlin, en 2009.", None),
 ([SP], 'Quel est le record du monde du saut en hauteur masculin ?', 'mètres', 2.45, 2, "Il est détenu depuis 1993 par le Cubain Javier Sotomayor.", None),
 ([SP], 'Combien de titres du Grand Chelem Rafael Nadal a-t-il gagnés en simple ?', 'titres', 22, 2, "Dont quatorze à Roland-Garros.", None),
 ([SP], 'Combien de titres du Grand Chelem Novak Djokovic a-t-il gagnés en simple ?', 'titres', 24, 2, "C'est le record chez les hommes.", 2025),
 ([SP], "Combien de Ballons d'or Lionel Messi a-t-il remportés ?", "Ballons d'or", 8, 2, "C'est le record absolu.", 2025),
 ([SP, G], 'Combien de joueurs compte une équipe de volley-ball sur le terrain ?', 'joueurs', 6, 1, "Les joueurs tournent d'une position à chaque fois que leur équipe reprend le service.", None),
 ([SP], 'Combien d’étapes compte le Tour de France ?', 'étapes', 21, 2, "Les coureurs ont droit à deux jours de repos.", None),
 ([SP, G], 'Combien de Coupes du monde de football le Brésil a-t-il gagnées ?', 'Coupes du monde', 5, 1, "C'est la seule équipe à avoir participé à toutes les éditions.", 2025),
 ([SP], 'Combien d’équipes participent à la Coupe du monde de football 2026 ?', 'équipes', 48, 2, "Elles étaient 32 de 1998 à 2022.", None),
 ([SP], 'Combien de minutes dure un match de rugby, hors arrêts de jeu ?', 'minutes', 80, 1, "Deux mi-temps de 40 minutes.", None),
 ([SP], 'Combien de minutes dure un round de boxe professionnelle ?', 'minutes', 3, 2, "Une minute de repos sépare chaque round.", None),
 ([SP], 'À combien de mètres du but se tire un penalty ?', 'mètres', 11, 2, "Soit 12 yards, une mesure anglaise.", None),
 ([SP, G], 'Quelle est la longueur d’un tour de piste d’athlétisme ?', 'mètres', 400, 1, "Mesurée dans le couloir intérieur.", None),
 ([SP], 'À quelle hauteur est le filet de volley-ball chez les hommes ?', 'mètres', 2.43, 3, "Pour les femmes, il est placé à 2,24 mètres.", None),
 ([SP], 'Quelle est la hauteur du filet de tennis en son centre ?', 'centimètres', 91.4, 3, "Il est un peu plus haut aux poteaux : 1,07 mètre.", None),
 ([SP, G], 'Combien de quilles faut-il renverser au bowling ?', 'quilles', 10, 1, "Un « strike », c'est les renverser toutes du premier coup.", None),
 ([SP], 'Quel est le diamètre d’un cercle de panier de basket ?', 'centimètres', 45.7, 3, "Le ballon y passe avec une vingtaine de centimètres de marge.", None),
 ([SP], 'Combien de médailles olympiques Michael Phelps a-t-il remportées ?', 'médailles', 28, 2, "Dont 23 en or, un record absolu.", None),
 ([SP], 'Combien de titres de champion du monde de Formule 1 Lewis Hamilton a-t-il gagnés ?', 'titres', 7, 2, "Il partage ce record avec Michael Schumacher.", 2025),
 ([SP], 'À quelle distance se trouve la cible au tir à l’arc olympique ?', 'mètres', 70, 3, "Le centre de la cible ne mesure que 12,2 centimètres de diamètre.", None),
 ([SP], 'Combien de minutes dure une mi-temps de handball ?', 'minutes', 30, 2, "Une équipe compte sept joueurs sur le terrain, gardien compris.", None),
 ([SP], 'Combien de Tours de France Bernard Hinault a-t-il gagnés ?', 'Tours', 5, 2, "Il est le dernier Français à avoir remporté l'épreuve, en 1985.", None),
 # ── Gastronomie ──────────────────────────────────────────
 ([FOOD], 'Selon une célèbre phrase du général de Gaulle, combien de variétés de fromage compte la France ?', 'fromages', 246, 3, "« Comment voulez-vous gouverner un pays qui a 246 variétés de fromage ? »", None),
 ([FOOD], "Quel pourcentage d'eau contient un concombre ?", '%', 95, 2, "C'est l'un des légumes les plus riches en eau.", None),
 ([FOOD], 'Combien de litres de lait faut-il pour fabriquer un kilo de comté ?', 'litres', 11, 3, "Une meule de 40 kilos demande environ 450 litres de lait.", None),
 ([FOOD, G], 'Combien de grammes de sucre contient une canette de 33 cl de Coca-Cola ?', 'grammes', 35, 2, "Soit l'équivalent d'environ sept morceaux de sucre.", None),
 ([FOOD], 'Combien de litres contient un magnum de champagne ?', 'litres', 1.5, 2, "Le nabuchodonosor contient 15 litres, soit vingt bouteilles.", None),
 ([FOOD], 'Quelle est la pression dans une bouteille de champagne ?', 'bars', 6, 3, "C'est environ trois fois la pression d'un pneu de voiture.", None),
 ([FOOD], 'Combien de jours dure au minimum l’affinage d’un comté ?', 'jours', 120, 3, "Les meilleures meules sont affinées plus d'un an et demi.", None),
 ([FOOD], 'Combien pèse une meule de comté ?', 'kilos', 40, 3, "Chaque meule porte une plaque de caséine verte qui permet de l'identifier.", None),
 ([FOOD, G], 'Combien d’étoiles peut obtenir, au maximum, un restaurant au guide Michelin ?', 'étoiles', 3, 1, "Trois étoiles : « une cuisine unique, qui vaut le voyage ».", None),
 ([FOOD], 'Combien de cépages sont autorisés pour élaborer le champagne ?', 'cépages', 7, 3, "Trois dominent : chardonnay, pinot noir et meunier.", None),
 ([FOOD], 'Combien pèse un œuf de poule moyen ?', 'grammes', 60, 2, "La coquille représente environ un dixième de ce poids.", None),
 ([FOOD], 'Combien d’œufs une poule pondeuse moderne pond-elle par an ?', 'œufs', 300, 2, "Ses ancêtres sauvages n'en pondaient qu'une dizaine à une vingtaine par an.", None),
 ([FOOD, HS], 'Combien de grammes de sel par jour recommande l’Organisation mondiale de la santé ?', 'grammes', 5, 2, "En France, on en consomme en moyenne près de deux fois plus.", None),
 ([FOOD], 'Combien de graines compte, en moyenne, la surface d’une fraise ?', 'graines', 200, 3, "Ces petits « grains » sont en fait les vrais fruits du fraisier.", None),
 ([FOOD, HS], 'Combien de kilocalories apporte un gramme de matières grasses ?', 'kcal', 9, 3, "C'est plus du double des glucides et des protéines, qui en apportent 4.", None),
 ([FOOD], 'Combien de verres de 12,5 cl peut-on servir avec une bouteille de vin standard ?', 'verres', 6, 2, "Une bouteille standard contient 75 centilitres.", None),
 ([FOOD], 'Combien pèse une baguette de tradition française ?', 'grammes', 250, 2, "Elle ne contient que farine, eau, sel et levure ou levain.", None),
 ([FOOD], 'Combien de grammes de sucre contiennent 100 grammes de Nutella ?', 'grammes', 56, 3, "Le sucre est son premier ingrédient.", None),
 ([FOOD], 'À quelle température cuit une pizza napolitaine au feu de bois ?', '°C', 450, 3, "Elle cuit en à peine 60 à 90 secondes.", None),
 ([FOOD], 'Quelle part de la production mondiale de cacao vient de Côte d’Ivoire ?', '%', 40, 3, "C'est le premier producteur mondial, devant le Ghana.", None),
 ([FOOD, G], 'Combien de minutes faut-il pour cuire un œuf à la coque ?', 'minutes', 3, 1, "Comptez six minutes pour un œuf mollet, une dizaine pour un œuf dur.", None),
 ([FOOD], 'Combien de litres de lait faut-il pour fabriquer un kilo de beurre ?', 'litres', 22, 3, "Ce qui reste après le barattage, le babeurre, se boit en Bretagne sous le nom de lait ribot.", None),
 ([FOOD], 'Quel est le taux minimum de matières grasses d’une crème fraîche entière ?', '%', 30, 3, "En dessous, on parle de crème « légère ».", None),
 ([FOOD], 'Combien de kilos de raisin faut-il, environ, pour une bouteille de vin ?', 'kilos', 1.2, 3, "On dit souvent qu'un pied de vigne donne à peu près une bouteille par an.", None),
 ([FOOD], 'Combien de litres d’eau conseille-t-on pour cuire 100 grammes de pâtes ?', 'litres', 1, 2, "On sale l'eau quand elle bout, avec environ 10 grammes de sel par litre.", None),
 ([FOOD], 'Combien d’ingrédients entrent dans une pâte à pain traditionnelle ?', 'ingrédients', 4, 2, "Farine, eau, sel et levure : rien d'autre.", None),
 ([FOOD], 'Combien de centilitres contient un expresso ?', 'centilitres', 3, 2, "En Italie, on le boit souvent debout, au comptoir.", None),
 ([FOOD], 'Quelle est la teneur minimale en cacao d’un chocolat noir en Europe ?', '%', 35, 3, "Un chocolat noir « dégustation » en contient en général au moins 70 %.", None),
 ([FOOD], 'Quel pourcentage de matières grasses doit contenir, au minimum, le beurre ?', '%', 82, 3, "Le reste est surtout de l'eau.", None),
]
