"""Indices facultatifs (champ `hint`), révélés à la demande du copilote pendant la question.
Un bon indice aide à raisonner (lieu, ordre de grandeur, point de comparaison) sans donner la réponse.
Appliqués par fact_check.apply() dans les scripts build_*.py."""

HINTS = {
    'est-0001': "Les mains et les pieds en contiennent à eux seuls plus de la moitié.",
    'est-0003': "Le sang représente environ 7 % du poids du corps.",
    'est-0004': "Il représente environ 2 % du poids du corps.",
    'est-0006': "C'est le même nombre chez presque tous les mammifères.",
    'est-0007': "Comptez nettement plus d'un an.",
    'est-0008': "Elle est bien plus longue qu'un autobus articulé (18 mètres).",
    'est-0011': "Il court plus vite qu'une voiture sur une route nationale à 80 km/h.",
    'est-0013': "Prenez votre pouls pendant 15 secondes et multipliez par quatre.",
    'est-0014': "Les capillaires, minuscules, en représentent l'essentiel.",
    'est-0015': "Une trentaine de Terres alignées tiendraient entre les deux.",
    'est-0016': "Elle fait plus de sept fois le tour de la Terre en une seconde.",
    'est-0017': "Bien plus chaud que la lave d'un volcan, autour de 1 000 °C.",
    'est-0019': "Environ trois fois l'âge de la Terre.",
    'est-0020': "Les dinosaures ont disparu il y a 66 millions d'années : c'est très récent en comparaison.",
    'est-0021': "Une centaine existent dans la nature ; les autres ont été créés en laboratoire.",
    'est-0022': "Là-haut, la pression de l'air est environ trois fois plus faible qu'au niveau de la mer.",
    'est-0023': "La lumière du Soleil met environ 8 minutes à faire le trajet.",
    'est-0024': "Le tour de la Terre mesure environ 40 000 kilomètres.",
    'est-0025': "Le mètre a été défini comme un dix-millionième du quart d'un méridien.",
    'est-0026': "Un avion de ligne vole à environ 80 % de cette vitesse.",
    'est-0027': "Six missions Apollo se sont posées sur la Lune.",
    'est-0028': "À peu près la distance Paris–Lyon à vol d'oiseau, mais à la verticale.",
    'est-0029': "Un tour complet lui prend environ une heure et demie.",
    'est-0030': "La lumière parcourt 300 000 km par seconde ; le Soleil est à 150 millions de km.",
    'est-0032': "Mars est plus loin du Soleil que la Terre : son année est plus longue.",
    'est-0033': "Elle est plus profonde que l'Everest n'est haut.",
    'est-0034': "Les avions de ligne volent à environ 10 à 12 kilomètres d'altitude.",
    'est-0035': "Un peu plus de la moitié de la hauteur de l'Everest.",
    'est-0036': "Il traverse l'Afrique du nord-est, du lac Victoria à la Méditerranée.",
    'est-0037': "Elle naît en Ardèche et se jette dans l'Atlantique à Saint-Nazaire.",
    'est-0038': "À peu près un carré de 740 kilomètres de côté.",
    'est-0039': "Environ trente fois la France métropolitaine.",
    'est-0040': "Les meilleurs nageurs la traversent en moins de huit heures.",
    'est-0041': "Les trains le franchissent en une vingtaine de minutes.",
    'est-0042': "C'est le continent qui compte le plus de pays.",
    'est-0043': "Comptez les étoiles du drapeau américain.",
    'est-0044': "Plus de la moitié du tour de la Terre.",
    'est-0045': "Environ deux fois et demie la tour Eiffel.",
    'est-0046': "Un peu moins de la moitié de la tour Eiffel.",
    'est-0047': "Un peu moins d'un tiers de la tour Eiffel.",
    'est-0048': "La hauteur d'un immeuble d'une centaine d'étages.",
    'est-0049': "Le deuxième étage est à 115 mètres de haut.",
    'est-0050': "Il coule de la Forêt-Noire, en Allemagne, jusqu'à la mer Noire.",
    'est-0051': "Un peu plus que la ville de Nice, qui compte environ 350 000 habitants.",
    'est-0052': "Environ 15 % de la population de l'Union européenne.",
    'est-0053': "L'Inde et la Chine en représentent à elles deux plus du tiers.",
    'est-0054': "Un peu moins que l'Inde, devenue le pays le plus peuplé du monde.",
    'est-0055': "La ville est petite : on la traverse à pied en moins de trois heures.",
    'est-0056': "Le Royaume-Uni l'a quittée en 2020 ; la Croatie est la dernière entrée, en 2013.",
    'est-0057': "Presque tous les pays du monde en sont membres.",
    'est-0058': "Les numéros vont de 01 (Ain) à 95 (Val-d'Oise), plus l'outre-mer.",
    'est-0059': "C'est plus que dans n'importe quel autre pays de l'Union européenne.",
    'est-0060': "Un navire met une dizaine d'heures pour le franchir.",
    'est-0061': "Le voyage complet traverse sept fuseaux horaires de décalage.",
    'est-0062': "Plus profond que quatre tours Eiffel empilées.",
    'est-0063': "N'oubliez pas les tout petits pays.",
    'est-0064': "Moins haut qu'un immeuble de vingt étages.",
    'est-0065': "Presque aussi grand que les États-Unis.",
    'est-0066': "Un peu moins que l'Île-de-France, qui en compte environ 12 millions.",
    'est-0067': "Environ dix-huit fois plus petite que la France métropolitaine.",
    'est-0068': "La hauteur d'un immeuble d'une trentaine d'étages.",
    'est-0069': "Il est bien plus petit que ce qu'imaginent les touristes.",
    'est-0071': "Le pays compte trois régions ; Bruxelles n'appartient à aucune province.",
    'est-0072': "Le tram de la côte la longe presque entièrement en deux heures et demie.",
    'est-0073': "Moins haut que le Grand Ballon, point culminant des Vosges (1 424 m).",
    'est-0074': "Un nombre rond.",
    'est-0075': "Près d'un an et demi.",
    'est-0076': "Trois grands voisins et un petit.",
    'est-0077': "La butte mesure 41 mètres de haut.",
    'est-0078': "Elle n'a jamais gagné Wimbledon.",
    'est-0079': "Il partage le record de victoires avec Anquetil, Hinault et Indurain.",
    'est-0080': "C'est la commune la plus peuplée de Belgique.",
    'est-0081': "Plusieurs dizaines de cloches, pour 27 tonnes au total.",
    'est-0082': "Le beffroi mesure 83 mètres de haut.",
    'est-0083': "La dernière victoire belge remonte à 1986.",
    'est-0084': "Dinant est la ville natale d'Adolphe Sax, l'inventeur du saxophone.",
    'est-0085': "Son dernier titre remonte à 2017.",
    'est-0086': "Environ une fois et demie Paris intra-muros (105 km²).",
    'est-0087': "Le premier, Léopold Ier, a régné 34 ans.",
    'est-0088': "C'est le plus long circuit du championnat de Formule 1.",
    'est-0089': "Moins de la moitié d'Anvers.",
    'est-0091': "Moins haut que le puy de Sancy, dans le Massif central (1 885 m).",
    'est-0092': "Plus profond que la tour Montparnasse n'est haute (210 m).",
    'est-0093': "Il occupe une partie du Great Glen, une faille qui coupe l'Écosse en deux.",
    'est-0094': "Environ 8 % de la population du Royaume-Uni.",
    'est-0095': "Pont ferroviaire en acier près d'Édimbourg, en Écosse, ouvert en 1890.",
    'est-0096': "Un minimum court : beaucoup de whiskies vieillissent dix ans ou plus.",
    'est-0097': "Le même minimum que pour le cognac.",
    'est-0098': "3 000 pieds, c'est environ 914 mètres.",
    'est-0100': "Il traverse le nord de l'Angleterre, d'une mer à l'autre.",
    'est-0102': "C'est la plus grande ville d'Écosse.",
    'est-0103': "Un peu moins que Glasgow.",
    'est-0105': "Il a joué à l'époque de Federer, Nadal et Djokovic.",
    'est-0106': "Ronnie O'Sullivan a égalé ce record en 2022.",
    'est-0108': "Environ un septième de la France métropolitaine.",
    'est-0109': "Elle remplace un escalier de onze écluses, démoli en 1933.",
    'est-0110': "Ce sont les plus grandes sculptures de chevaux du monde.",
    'est-0111': "C'est le plus grand stade d'Écosse.",
    'est-0112': "On y monte à pied en moins d'une heure depuis le palais de Holyrood.",
    'est-0113': "On la parcourt en général en une semaine de marche.",
    'est-0114': "Plus d'une centaine de députés.",
    'est-0115': "C'est la tour gothique noire près de la gare de Waverley.",
    'est-0117': "Le dernier en date, « Mourir peut attendre », est sorti en 2021.",
    'est-0118': "Plus de trois heures.",
    'est-0119': "Elle a duré de 1994 à 2004.",
    'est-0120': "Dix saisons d'environ 24 épisodes.",
    'est-0121': "Un livre par année d'études à Poudlard.",
    'est-0122': "Le dernier de la liste est Mew.",
    'est-0130': "Bien plus long qu'un tube radio classique de trois minutes.",
    'est-0132': "Un nouvel album paraît tous les deux ans environ depuis 2013.",
    'est-0137': "Huit saisons, dont une dernière très courte.",
    'est-0138': "Elle a remporté l'album de l'année pour la première fois en 2025.",
    'est-0141': "Un album d'environ 42 minutes.",
    'est-0142': "Toutes ses victoires datent d'avant 1980.",
    'est-0143': "Le premier film est sorti en 2001.",
    'est-0155': "Deux de moins que Novak Djokovic.",
    'est-0156': "Deux de plus que Rafael Nadal.",
    'est-0170': "Il a participé à cinq Jeux olympiques, de 2000 à 2016.",
    'est-0175': "Un nombre précis, pas un chiffre rond.",
    'est-0177': "Le fromage garde surtout les protéines et la matière grasse du lait.",
    'est-0178': "Environ 10,6 grammes de sucre pour 100 millilitres.",
    'est-0179': "Il équivaut à deux bouteilles classiques.",
    'est-0180': "Un pneu de voiture est gonflé à environ 2 bars.",
    'est-0182': "Elle mesure environ 60 centimètres de diamètre pour 10 d'épaisseur.",
    'est-0185': "Le calibre « gros » commence à 63 grammes.",
    'est-0186': "Presque un par jour.",
    'est-0187': "Environ une cuillère à café rase.",
    'est-0191': "Elle mesure environ 55 à 65 centimètres de long.",
    'est-0193': "Bien plus chaud qu'un four de cuisine, qui monte à environ 250 °C.",
    'est-0196': "La crème ne représente qu'une petite partie du lait.",
    'est-0198': "Une bouteille contient 75 centilitres.",
    'est-0201': "Il se boit en deux ou trois gorgées.",
}
