# Nouvelles questions « Quelle année ? » (étape 3). Format :
# (packs, catégorie, énoncé, année, difficulté, anecdote)
G, SC, BE, POP, SP, HS, GEO, FOOD = 'general', 'scotland', 'belgium', 'pop', 'sport', 'history-science', 'geo-travel', 'food'
ITEMS = [
 # ── Écosse ───────────────────────────────────────────────
 ([SC, HS], 'Littérature', 'La naissance du poète écossais Robert Burns', 1759, 3, "Chaque 25 janvier, les Écossais fêtent sa naissance par un dîner où l'on récite son poème au haggis."),
 ([SC, HS], 'Histoire', 'La bataille de Bannockburn, victoire de Robert Bruce', 1314, 3, "L'armée écossaise y a battu une armée anglaise bien plus nombreuse."),
 ([SC, HS], 'Histoire', "Le roi d'Écosse Jacques VI devient aussi roi d'Angleterre", 1603, 3, "On parle d'« union des couronnes » : un seul roi, mais encore deux royaumes distincts."),
 ([SC, HS], 'Histoire', 'La bataille de Culloden, dans les Highlands', 1746, 3, "C'est souvent présenté comme la dernière bataille rangée livrée sur le sol britannique."),
 ([SC, GEO], 'Monuments', 'La mise en service du Forth Bridge, le pont ferroviaire rouge près d’Édimbourg', 1890, 3, "Il est inscrit au patrimoine mondial de l'Unesco."),
 ([SC, G], 'Politique', "Le référendum sur l'indépendance de l'Écosse", 2014, 1, "Le « non » l'a emporté avec environ 55 % des voix."),
 ([SC, HS], 'Inventions', 'Le brevet de la machine à vapeur améliorée de James Watt', 1769, 3, "Le watt, l'unité de puissance, porte le nom de cet ingénieur écossais."),
 ([SC, POP], 'Cinéma', 'La naissance de Sean Connery, à Édimbourg', 1930, 3, "Avant de devenir James Bond, il avait notamment été livreur de lait dans sa ville natale."),
 ([SC, POP], 'Cinéma', 'La sortie du tout premier film de James Bond, « James Bond 007 contre Dr No »', 1962, 2, "Ian Fleming a emprunté le nom de son héros à un ornithologue américain."),
 ([SC, HS], 'Inventions', "La première démonstration publique de la télévision par l'Écossais John Logie Baird", 1926, 3, "Ses premiers essais montraient le visage d'une marionnette de ventriloque."),
 ([SC, HS], 'Histoire', 'L’exécution de Marie Stuart, reine d’Écosse', 1587, 3, "Elle a été exécutée sur ordre de sa cousine Élisabeth Ire d'Angleterre."),
 ([SC, SP], 'Golf', 'Le tout premier Open britannique de golf, à Prestwick', 1860, 3, "Le vainqueur ne recevait pas de coupe mais une ceinture en cuir rouge."),
 ([SC, SP], 'Football', 'Le tout premier match international de football, Écosse contre Angleterre', 1872, 3, "Il s'est terminé sur un score de 0 à 0, à Glasgow."),
 ([SC, POP], 'Cinéma', 'La sortie du film « Trainspotting »', 1996, 2, "Le film suit une bande de jeunes d'Édimbourg, d'après le roman d'Irvine Welsh."),
 ([SC, POP], 'Livres', 'La publication en livre de « L’Île au trésor » de Robert Louis Stevenson', 1883, 3, "Stevenson, né à Édimbourg, a imaginé l'histoire à partir d'une carte dessinée pour son beau-fils."),
 ([SC, POP], 'Livres', 'La première aventure de Sherlock Holmes, « Une étude en rouge »', 1887, 3, "Son créateur, Arthur Conan Doyle, était un médecin né à Édimbourg."),
 ([SC, GEO], 'Monuments', "L'inauguration de la Roue de Falkirk, l'ascenseur à bateaux rotatif", 2002, 3, "Elle soulève les bateaux d'un canal à l'autre en quelques minutes, en tournant comme une grande roue."),
 ([SC, SP], 'Tennis', "La première victoire d'Andy Murray à Wimbledon", 2013, 2, "Aucun Britannique n'avait gagné le simple messieurs depuis Fred Perry en 1936."),
 ([SC, POP], 'Légendes', 'La célèbre « photo du chirurgien » du monstre du Loch Ness', 1934, 3, "Soixante ans plus tard, on a révélé que le « monstre » était un jouet coiffé d'une fausse tête."),
 ([SC, POP], 'Festivals', 'Le tout premier Festival international d’Édimbourg', 1947, 3, "Huit troupes non invitées ont joué en marge : c'est la naissance du « Fringe »."),
 ([SC, HS], 'Économie', "La publication de « La Richesse des nations » d'Adam Smith", 1776, 3, "Ce philosophe écossais est souvent présenté comme le père de l'économie moderne."),
 ([SC, HS], 'Inventions', 'Le brevet du pneu gonflable de l’Écossais John Boyd Dunlop', 1888, 3, "Il l'a d'abord imaginé pour le tricycle de son jeune fils."),
 ([SC, HS], 'Histoire', 'L’exécution de William Wallace, le héros de « Braveheart »', 1305, 3, "Ce chef de la résistance écossaise a été exécuté à Londres."),
 # ── Belgique ─────────────────────────────────────────────
 ([BE, SP], 'Cyclisme', 'La toute première course Liège-Bastogne-Liège', 1892, 3, "Surnommée « la Doyenne », c'est la plus ancienne des grandes classiques cyclistes."),
 ([BE, HS, G], 'Histoire', 'La bataille de Waterloo', 1815, 1, "Waterloo se trouve en Belgique, à une vingtaine de kilomètres au sud de Bruxelles."),
 ([BE, POP], 'Chanson', 'La sortie de « Ne me quitte pas » de Jacques Brel', 1959, 3, "C'est l'une des chansons francophones les plus reprises, jusqu'en anglais par Nina Simone."),
 ([BE, POP], 'Bande dessinée', 'La première apparition de Spirou, dans le journal du même nom', 1938, 3, "« Spirou » veut dire « écureuil » en wallon, d'où son compagnon Spip."),
 ([BE, POP], 'Bande dessinée', 'La première apparition de Gaston Lagaffe', 1957, 3, "Il est d'abord apparu comme un simple figurant qui errait dans les pages du journal Spirou."),
 ([BE, HS], 'Monuments', 'La statue en bronze du Manneken-Pis par Jérôme Duquesnoy', 1619, 3, "Il possède une garde-robe de plus de mille costumes."),
 ([BE, POP, HS], 'Musique', "Le brevet du saxophone d'Adolphe Sax", 1846, 2, "Adolphe Sax était né à Dinant, où des saxophones géants décorent aujourd'hui un pont."),
 ([BE, SP], 'Tennis', 'La première victoire de Justine Henin à Roland-Garros', 2003, 3, "Cette année-là, la finale opposait deux Belges : Justine Henin et Kim Clijsters."),
 ([BE, POP], 'Chanson', 'La sortie du tube « Alors on danse » de Stromae', 2009, 2, "Le nom Stromae, c'est le mot « maestro » en verlan."),
 ([BE, HS], 'Histoire', 'La prestation de serment de Léopold Ier, premier roi des Belges', 1831, 2, "C'est pour cette raison que la fête nationale belge tombe le 21 juillet."),
 ([BE, HS], 'Société', 'Le droit de vote des femmes aux élections législatives belges', 1948, 3, "Elles pouvaient déjà voter aux élections communales depuis 1921."),
 ([BE, HS, GEO], 'Transports', 'La première ligne de chemin de fer belge, entre Bruxelles et Malines', 1835, 3, "C'était la première ligne de voyageurs du continent européen."),
 ([BE, SP], 'Football', 'Le tout premier match officiel des Diables rouges, contre la France', 1904, 3, "C'était aussi le premier match de l'équipe de France : 3 à 3."),
 ([BE, SP], 'Football', 'La troisième place de la Belgique à la Coupe du monde en Russie', 2018, 2, "C'est la meilleure performance de l'histoire de l'équipe belge en Coupe du monde."),
 ([BE, FOOD], 'Gastronomie', 'L’invention de la praline par Jean Neuhaus, à Bruxelles', 1912, 3, "Trois ans plus tard, sa femme inventait le « ballotin », la boîte qui protège les pralines."),
 ([BE, HS], 'Histoire', 'La fondation de l’université de Louvain', 1425, 3, "Érasme y a fondé un collège pour enseigner le latin, le grec et l'hébreu."),
 ([BE, POP], 'Festivals', 'La toute première édition du festival Tomorrowland', 2005, 3, "Ce festival de musique électronique se tient à Boom, entre Anvers et Bruxelles."),
 ([BE, HS], 'Politique', 'La fin de la plus longue crise gouvernementale belge, avec un gouvernement Di Rupo', 2011, 3, "La crise avait commencé après les élections législatives de juin 2010."),
 ([BE, HS], 'Art', "L'achèvement du retable de « L'Agneau mystique » des frères Van Eyck", 1432, 3, "C'est l'une des œuvres les plus volées de l'histoire : un de ses panneaux n'a jamais été retrouvé."),
 ([BE, SP], 'Tennis', "La victoire de Kim Clijsters à l'US Open, quelques mois après son retour", 2009, 3, "Elle avait arrêté sa carrière deux ans plus tôt et était devenue maman entre-temps."),
 # ── Gastronomie ──────────────────────────────────────────
 ([FOOD, POP], 'Boissons', 'La création du Coca-Cola, à Atlanta', 1886, 2, "Il était vendu au départ comme une boisson médicinale, en pharmacie."),
 ([FOOD], 'Restauration', 'L’ouverture du tout premier restaurant des frères McDonald, en Californie', 1940, 3, "Les frères McDonald vendaient d'abord surtout du barbecue."),
 ([FOOD], 'Marques', 'La création de la marque Danone, à Barcelone', 1919, 3, "Son nom vient de « Danon », le surnom du fils du fondateur, Daniel."),
 ([FOOD], 'Chocolat', 'La création du Toblerone, en Suisse', 1908, 2, "Son nom combine celui du chocolatier Tobler et « torrone », le nougat en italien."),
 ([FOOD, POP], 'Confiserie', 'Le lancement des M&M’s aux États-Unis', 1941, 3, "Ils ont d'abord été fournis aux soldats américains, car l'enrobage empêche le chocolat de fondre."),
 ([FOOD], 'Sauces', 'Le lancement du ketchup Heinz', 1876, 3, "Le mot « ketchup » viendrait d'une sauce de poisson fermenté venue d'Asie."),
 ([FOOD, HS], 'Vins', 'Le classement officiel des grands vins de Bordeaux', 1855, 3, "Il a été établi pour l'Exposition universelle de Paris, à la demande de Napoléon III."),
 ([FOOD], 'Fromages', 'La loi qui protège le Roquefort, première appellation d’origine fromagère', 1925, 3, "Il doit être affiné dans les caves naturelles de Roquefort-sur-Soulzon."),
 ([FOOD, POP], 'Confiserie', 'Le lancement de l’œuf Kinder Surprise', 1974, 2, "Il est interdit à la vente aux États-Unis à cause du jouet caché à l'intérieur."),
 ([FOOD], 'Confiserie', 'Le brevet de la machine électrique à barbe à papa', 1897, 3, "L'un des deux inventeurs de la machine était… dentiste."),
 ([FOOD], 'Boissons', 'Le lancement de la boisson Red Bull, en Autriche', 1987, 3, "Elle s'inspire d'une boisson énergisante thaïlandaise, Krating Daeng."),
 ([FOOD, POP], 'Boissons', 'L’ouverture du tout premier Starbucks, à Seattle', 1971, 2, "Son nom vient d'un personnage du roman « Moby Dick »."),
 ([FOOD], 'Snacks', 'Le lancement des chips Pringles', 1968, 3, "L'inventeur de leur boîte a demandé qu'une partie de ses cendres y soit placée."),
 ([FOOD], 'Chefs', 'La troisième étoile Michelin de Paul Bocuse', 1965, 3, "Il l'a conservée jusqu'à sa mort, plus de cinquante ans plus tard."),
 ([FOOD], 'Boissons', 'Le lancement de l’Orangina, à la Foire de Marseille', 1936, 3, "Sa bouteille ronde imite la forme d'une orange."),
 ([FOOD, G], 'Patrimoine', 'L’inscription du repas gastronomique des Français à l’Unesco', 2010, 2, "La même année, la cuisine mexicaine a aussi été inscrite au patrimoine immatériel."),
 ([FOOD], 'Fromages', 'La création de La Vache qui rit', 1921, 2, "Le dessin de la vache est signé Benjamin Rabier, célèbre illustrateur d'animaux."),
 ([FOOD], 'Confiserie', 'La création de la marque Haribo, à Bonn', 1920, 3, "Haribo, c'est HAns RIegel BOnn : le nom du fondateur et de sa ville."),
 ([FOOD], 'Chocolat', 'Le lancement des Ferrero Rocher', 1982, 3, "Leur nom évoque le rocher de Massabielle, à Lourdes."),
 ([FOOD, GEO], 'Marchés', 'L’ouverture du marché international de Rungis', 1969, 3, "Il a remplacé les Halles de Paris, surnommées « le ventre de Paris » par Zola."),
 ([FOOD], 'Alcools', 'La fondation de la maison de cognac Hennessy', 1765, 3, "Son fondateur, Richard Hennessy, était un officier irlandais au service du roi de France."),
 ([FOOD], 'Sauces', 'Le lancement de la sauce Tabasco, en Louisiane', 1868, 3, "Elle est toujours produite sur l'île Avery, en Louisiane."),
 ([FOOD], 'Bières', 'Le rachat par Gerard Heineken de sa première brasserie, à Amsterdam', 1864, 3, "La brasserie s'appelait « La Botte de foin »."),
 ([FOOD], 'Confiserie', 'Le lancement du Carambar', 1954, 3, "Les blagues sur l'emballage ne sont apparues qu'à la fin des années 1960."),
 ([FOOD], 'Pâtisserie', 'La première Coupe du monde de la pâtisserie, à Lyon', 1989, 3, "Elle se dispute tous les deux ans pendant le Sirha, le grand salon de la restauration."),
 ([FOOD, G], 'Biscuits', 'La création du Petit Beurre LU, à Nantes', 1886, 2, "Le biscuit compte 52 dents, comme les 52 semaines de l'année."),
 # ── Sport ────────────────────────────────────────────────
 ([SP], 'Tennis', 'Le premier Roland-Garros ouvert aux joueurs professionnels', 1968, 3, "Ce fut le premier tournoi du Grand Chelem de l'ère Open."),
 ([SP, G], 'Football', 'La toute première Coupe du monde de football, en Uruguay', 1930, 2, "Seules quatre équipes européennes ont fait le voyage en bateau jusqu'en Amérique du Sud."),
 ([SP], 'Automobile', 'La toute première édition des 24 Heures du Mans', 1923, 2, "Le circuit emprunte en partie des routes ordinaires, ouvertes le reste de l'année."),
 ([SP], 'Athlétisme', "Le record du monde du 100 mètres d'Usain Bolt en 9,58 secondes", 2009, 2, "Il l'a établi à Berlin, et ce record tient toujours."),
 ([SP, HS], 'Olympisme', 'Les derniers Jeux olympiques d’été à Paris avant ceux de 2024', 1924, 3, "C'est lors de ces Jeux que la devise « Plus vite, plus haut, plus fort » a été utilisée pour la première fois."),
 ([SP], 'Judo', 'Le premier titre olympique de Teddy Riner', 2012, 3, "Il était déjà champion du monde dès l'âge de 18 ans."),
 ([SP, G], 'Football', 'Le coup de tête de Zinédine Zidane en finale de Coupe du monde', 2006, 1, "C'était le dernier match de sa carrière professionnelle."),
 ([SP, G], 'Football', 'La deuxième étoile de la France, en Coupe du monde en Russie', 2018, 1, "Kylian Mbappé est devenu le deuxième adolescent à marquer en finale, après Pelé."),
 ([SP], 'Football américain', 'Le tout premier Super Bowl', 1967, 3, "Les places les plus chères coûtaient alors 12 dollars."),
 ([SP], 'Cyclisme', 'Le premier Tour de France Femmes organisé par les organisateurs du Tour', 2022, 3, "La Néerlandaise Annemiek van Vleuten a remporté cette première édition."),
 ([SP], 'Tennis', 'La première victoire de Rafael Nadal à Roland-Garros', 2005, 2, "Il a fini par remporter le tournoi quatorze fois."),
 ([SP], 'Basket', 'Le premier titre NBA de Michael Jordan avec les Chicago Bulls', 1991, 3, "Il a gagné six titres, à chaque fois élu meilleur joueur de la finale."),
 ([SP], 'Rugby', 'La toute première Coupe du monde de rugby', 1987, 2, "La Nouvelle-Zélande l'a remportée face à la France en finale."),
 ([SP], 'Athlétisme', 'Le tout premier marathon de New York', 1970, 3, "Seuls 127 coureurs y ont participé, en tournant dans Central Park."),
 ([SP], 'Formule 1', 'La toute première course du championnat du monde de Formule 1, à Silverstone', 1950, 3, "Le roi George VI assistait à la course."),
 ([SP], 'Formule 1', 'Le premier titre de champion du monde de Michael Schumacher', 1994, 3, "Il a fini sa carrière avec sept titres de champion du monde."),
 ([SP], 'Football', 'La création de la Ligue des champions sous ce nom', 1992, 3, "Marseille l'a gagnée dès sa première saison."),
 ([SP], 'Football', 'Le tout premier Ballon d’or', 1956, 3, "Il a été remporté par l'Anglais Stanley Matthews, à 41 ans."),
 ([SP, G], 'Tennis', 'La victoire de Yannick Noah à Roland-Garros', 1983, 2, "Aucun Français n'a remporté le simple messieurs depuis."),
 ([SP], 'Athlétisme', 'Le premier saut à la perche au-dessus de six mètres, par Sergueï Bubka', 1985, 3, "Bubka a battu le record du monde 35 fois, en salle et en plein air."),
 ([SP, HS], 'Olympisme', 'Les premières femmes en compétition aux Jeux olympiques', 1900, 3, "La Britannique Charlotte Cooper est devenue la première championne olympique, en tennis."),
 ([SP], 'Voile', 'Le départ du tout premier Vendée Globe', 1989, 3, "C'est un tour du monde à la voile, en solitaire, sans escale et sans assistance."),
 ([SP], 'Inventions', 'L’invention du volley-ball', 1895, 3, "Son inventeur voulait un sport moins brutal que le basket, inventé quatre ans plus tôt."),
 ([SP, HS], 'Inventions', 'L’invention du basket-ball par James Naismith', 1891, 3, "Les premiers paniers étaient de vrais paniers à pêches."),
 ([SP, G], 'Football', "La victoire de la France à l'Euro, avec Michel Platini", 1984, 2, "Michel Platini a marqué neuf buts durant ce tournoi."),
 ([SP], 'Olympisme', 'Les Jeux olympiques d’hiver d’Albertville', 1992, 2, "La cérémonie d'ouverture avait été mise en scène par Philippe Decouflé."),
 ([SP, G], 'Olympisme', 'Les Jeux olympiques avec une cérémonie d’ouverture sur la Seine', 2024, 1, "Les délégations ont défilé sur des bateaux, et non dans un stade."),
 ([SP], 'Football', 'La création du Paris Saint-Germain', 1970, 3, "Le club est né de la fusion du Paris FC et du Stade Saint-Germain."),
 ([SP, GEO], 'Automobile', 'Le départ du tout premier Paris-Dakar', 1978, 3, "Son créateur, Thierry Sabine, en a eu l'idée après s'être perdu dans le désert libyen."),
 ([SP], 'Natation', 'La première traversée de la Manche à la nage, par Matthew Webb', 1875, 3, "Il a mis près de 22 heures, en nageant la brasse."),
 ([SP], 'Tennis', 'Le tout premier tournoi de Wimbledon', 1877, 3, "Seuls des hommes y participaient : le tournoi féminin n'est arrivé que sept ans plus tard."),
 ([SP], 'Cyclisme', 'La première victoire de Bernard Hinault au Tour de France', 1978, 3, "Il a remporté le Tour cinq fois."),
 ([SP], 'Athlétisme', 'La médaille d’or de Marie-José Pérec sur 400 mètres à Barcelone', 1992, 3, "Elle a réalisé le doublé 200 m - 400 m quatre ans plus tard, à Atlanta."),
 # ── Géographie & voyages ─────────────────────────────────
 ([GEO, G], 'Monuments', "L'inauguration de la statue de la Liberté, à New York", 1886, 2, "Sa structure métallique intérieure a été conçue par Gustave Eiffel."),
 ([GEO], 'Voyages', "L'ouverture du canal de Panama", 1914, 2, "Les navires y sont hissés par des écluses jusqu'à un lac situé à 26 mètres d'altitude."),
 ([GEO, SP], 'Exploration', 'La première ascension de l’Everest', 1953, 2, "Edmund Hillary et Tenzing Norgay n'ont passé qu'une quinzaine de minutes au sommet."),
 ([GEO], 'Aviation', 'Le premier vol commercial du Concorde', 1976, 2, "Il reliait Paris à New York en environ 3 h 30."),
 ([GEO, HS, G], 'Exploration', "L'arrivée de Christophe Colomb en Amérique", 1492, 1, "Il pensait avoir atteint les Indes, d'où le nom d'« Indiens » donné aux habitants."),
 ([GEO, HS], 'Exploration', 'Le retour en Espagne du premier tour du monde, lancé par Magellan', 1522, 3, "Magellan lui-même n'est pas revenu : il a été tué aux Philippines en chemin."),
 ([GEO], 'Monuments', "L'inauguration du Golden Gate Bridge, à San Francisco", 1937, 3, "Sa couleur officielle s'appelle « orange international »."),
 ([GEO, G], 'Transports', "L'ouverture de la première ligne du métro de Paris", 1900, 2, "Elle a été inaugurée pendant l'Exposition universelle."),
 ([GEO, HS], 'Transports', "L'ouverture du tout premier métro du monde, à Londres", 1863, 3, "Les premières rames étaient tirées par des locomotives à vapeur."),
 ([GEO, HS], 'Aviation', 'La traversée de l’Atlantique en avion en solitaire de Charles Lindbergh', 1927, 2, "Il a relié New York à Paris en 33 heures et demie, sans dormir."),
 ([GEO], 'Transports', "L'ouverture du tunnel du Mont-Blanc", 1965, 3, "Il mesure un peu moins de 12 kilomètres et relie la France à l'Italie."),
 ([GEO, G], 'Transports', 'La mise en service commerciale du TGV, entre Paris et Lyon', 1981, 2, "Les premières rames arboraient une livrée orange restée célèbre."),
 ([GEO], 'Monuments', "L'inauguration du viaduc de Millau", 2004, 2, "Le sommet de l'un de ses pylônes culmine plus haut que la tour Eiffel."),
 ([GEO, POP, G], 'Loisirs', "L'ouverture de Disneyland Paris", 1992, 1, "Il s'appelait alors Euro Disney Resort."),
 ([GEO, HS, G], 'Histoire', "La réunification de l'Allemagne", 1990, 1, "Elle a eu lieu moins d'un an après la chute du mur de Berlin."),
 ([GEO, HS, G], 'Histoire', "La déclaration d'indépendance des États-Unis", 1776, 1, "Elle a été adoptée un 4 juillet, devenu jour de fête nationale."),
 ([GEO, HS], 'Histoire', 'La rétrocession de Hong Kong à la Chine', 1997, 2, "Le territoire était britannique depuis plus de 150 ans."),
 ([GEO], 'Monuments', "L'inauguration de la Burj Khalifa, à Dubaï", 2010, 2, "Elle dépasse les 800 mètres de haut."),
 ([GEO], 'Transports', "L'ouverture du pont de l'Øresund, entre le Danemark et la Suède", 2000, 3, "Le trajet commence par un tunnel sous la mer, puis se poursuit sur le pont."),
 ([GEO, HS], 'Exploration', 'La « découverte » du Machu Picchu par Hiram Bingham', 1911, 3, "Des paysans de la région connaissaient le site bien avant son arrivée."),
 ([GEO], 'Nature', 'La création de Yellowstone, premier parc national du monde', 1872, 3, "Il est en grande partie situé au-dessus d'un supervolcan."),
 ([GEO], 'Voyages', "L'entrée en vigueur de l'espace Schengen", 1995, 3, "Schengen est un petit village du Luxembourg."),
 ([GEO, G], 'Monnaie', 'L’arrivée des pièces et billets en euros dans les porte-monnaie', 2002, 1, "Douze pays ont changé de monnaie le même jour."),
 ([GEO, HS], 'Histoire', 'La prise de Constantinople par les Ottomans', 1453, 3, "Pour beaucoup d'historiens, cette date marque la fin du Moyen Âge."),
 ([GEO, HS], 'Aviation', 'La première traversée de la Manche en avion, par Louis Blériot', 1909, 2, "Le vol de Calais à Douvres a duré environ 37 minutes."),
 ([GEO, POP], 'Monuments', "L'inauguration de l'Opéra de Sydney", 1973, 3, "Son architecte, le Danois Jørn Utzon, ne l'a jamais vu terminé."),
 ([GEO], 'Aviation', 'Le premier vol commercial de l’Airbus A380', 2007, 3, "Il a d'abord volé pour Singapore Airlines, entre Singapour et Sydney."),
 ([GEO, SP], 'Automobile', 'Le tout premier Grand Prix de Monaco', 1929, 3, "Le vainqueur courait sous un pseudonyme : « Williams »."),
 ([GEO, HS], 'Villes', 'La fondation de Montréal', 1642, 3, "La ville s'appelait d'abord Ville-Marie."),
 ([GEO, HS], 'Villes', 'La fondation de Québec par Samuel de Champlain', 1608, 3, "C'est l'une des plus anciennes villes d'Amérique du Nord."),
 ([GEO, HS], 'Histoire', "L'achat de l'Alaska par les États-Unis à la Russie", 1867, 3, "Il a coûté environ 7 millions de dollars, soit quelques centimes l'hectare."),
 ([GEO, HS], 'Monuments', "L'installation de Louis XIV et de la cour à Versailles", 1682, 3, "Avant d'être un palais, Versailles était un pavillon de chasse de Louis XIII."),
 ([GEO], 'Monuments', "L'ouverture du Centre Pompidou, à Paris", 1977, 3, "Ses tuyaux colorés ont chacun un rôle : bleu pour l'air, vert pour l'eau, jaune pour l'électricité."),
 ([GEO, POP], 'Transports', 'Le premier voyage de l’Orient-Express', 1883, 3, "Agatha Christie y a situé l'un de ses plus célèbres romans policiers."),
 ([GEO, HS], 'Voyages', "L'inauguration du canal du Midi", 1681, 3, "Il relie Toulouse à la Méditerranée et, par la Garonne, l'Atlantique à la Méditerranée."),
 ([GEO, HS, BE], 'Europe', 'La signature du traité de Rome, qui crée la Communauté économique européenne', 1957, 3, "Six pays l'ont signé, dont la France et la Belgique."),
 ([GEO, HS], 'Monuments', "L'ouverture du musée du Louvre au public", 1793, 3, "La pyramide de verre n'a été ajoutée que près de deux siècles plus tard."),
 # ── Culture pop ──────────────────────────────────────────
 ([POP], 'Bande dessinée', "La sortie du tout premier album d'Astérix, « Astérix le Gaulois »", 1961, 2, "Le personnage était apparu deux ans plus tôt dans le journal Pilote."),
 ([POP, G], 'Cinéma', 'La sortie du film « Titanic » de James Cameron', 1997, 1, "Il a longtemps été le plus gros succès de l'histoire du cinéma."),
 ([POP, SC], 'Cinéma', 'La sortie du premier film « Harry Potter » au cinéma', 2001, 1, "Daniel Radcliffe avait 11 ans au début du tournage."),
 ([POP], 'Télévision', 'La diffusion du premier épisode de la série « Les Simpson »', 1989, 2, "La famille était d'abord apparue dans de courts sketches dès 1987."),
 ([POP, G], 'Musique', "La sortie de l'album « Thriller » de Michael Jackson", 1982, 2, "C'est l'album le plus vendu de l'histoire de la musique."),
 ([POP], 'Cinéma', 'La sortie du premier film « Toy Story »', 1995, 2, "C'était le tout premier long métrage entièrement réalisé en images de synthèse."),
 ([POP], 'Jeux vidéo', 'La sortie de la console Nintendo Switch', 2017, 2, "On peut y jouer aussi bien sur la télévision qu'en mode portable."),
 ([POP], 'Jeux vidéo', 'La sortie du jeu « Pac-Man » au Japon', 1980, 3, "Sa forme viendrait d'une pizza à laquelle il manque une part."),
 ([POP], 'Jeux vidéo', 'La sortie du jeu « Super Mario Bros. »', 1985, 2, "Mario s'appelait d'abord « Jumpman »."),
 ([POP], 'Cinéma', "La sortie de « Blanche-Neige et les Sept Nains », de Disney", 1937, 2, "Pendant sa fabrication, on surnommait ce projet risqué « la folie de Disney »."),
 ([POP], 'Cinéma', "La toute première édition du Festival de Cannes à se tenir réellement", 1946, 3, "La première édition, prévue en 1939, avait été annulée à cause de la guerre."),
 ([POP], 'Musique', "La sortie de « Bohemian Rhapsody » de Queen", 1975, 2, "Sa maison de disques la trouvait trop longue pour passer à la radio."),
 ([POP], 'Télévision', 'La diffusion du premier épisode de « Friends »', 1994, 2, "Les six acteurs principaux ont fini par toucher un million de dollars chacun par épisode."),
 ([POP], 'Télévision', 'La diffusion du premier épisode de « Game of Thrones »', 2011, 2, "Une grande partie de la série a été tournée en Irlande du Nord."),
 ([POP, HS], 'Internet', 'La création de YouTube', 2005, 2, "La toute première vidéo, d'une vingtaine de secondes, montrait des éléphants dans un zoo."),
 ([POP, G], 'Internet', 'La création de Facebook', 2004, 1, "Il était d'abord réservé aux étudiants de l'université Harvard."),
 ([POP], 'Cinéma', "La sortie du film « E.T. l'extra-terrestre »", 1982, 2, "Pour sa voix, l'équipe s'est notamment inspirée de celle d'une femme âgée qui fumait beaucoup."),
 ([POP], 'Cinéma', 'La sortie du film « Les Bronzés »', 1978, 3, "Le film a été tourné dans un vrai Club Med, en Côte d'Ivoire."),
 ([POP], 'Musique', 'Le tout premier disque de Johnny Hallyday', 1960, 3, "Il n'avait que 16 ans."),
 ([POP], 'Cinéma', 'La sortie du film « La Grande Vadrouille »', 1966, 3, "Il est resté plus de quarante ans le plus grand succès d'un film français en salles."),
 ([POP], 'Jeux vidéo', 'La sortie des premiers jeux Pokémon, au Japon', 1996, 2, "L'idée viendrait de la passion d'enfance de son créateur pour la collection d'insectes."),
 ([POP], 'Cinéma', 'La sortie du film « Les Visiteurs »', 1993, 2, "Jacquouille la Fripouille y est interprété par Christian Clavier."),
 ([POP], 'Cinéma', 'La sortie du film « Bienvenue chez les Ch’tis »', 2008, 2, "Il a dépassé « La Grande Vadrouille » au box-office français."),
 ([POP], 'Cinéma', 'La sortie du film « Intouchables »', 2011, 2, "Omar Sy a reçu le César du meilleur acteur pour ce rôle."),
 ([POP], 'Cinéma', 'La sortie du film « Le Fabuleux Destin d’Amélie Poulain »', 2001, 2, "Une grande partie du film a été tournée à Montmartre, dans un vrai café."),
 ([POP], 'Jeux vidéo', 'La sortie de la version complète du jeu « Minecraft »', 2011, 3, "C'est le jeu vidéo le plus vendu de l'histoire."),
 ([POP], 'Cinéma', 'La sortie du film « Le Seigneur des anneaux : la Communauté de l’anneau »', 2001, 2, "Toute la trilogie a été tournée d'un seul bloc, en Nouvelle-Zélande."),
 ([POP, G], 'Cinéma', 'La sortie du dessin animé « Le Roi lion »', 1994, 1, "Simba veut dire « lion » en swahili."),
 ([POP], 'Cinéma', 'La sortie de « La Reine des neiges », de Disney', 2013, 1, "La chanson « Libérée, délivrée » a été enregistrée dans plus de 40 langues."),
 ([POP], 'Télévision', 'La première de l’émission « Questions pour un champion »', 1988, 3, "Julien Lepers l'a présentée pendant 28 ans."),
 ([POP], 'Musique', "La sortie de l'album « Abbey Road » des Beatles", 1969, 3, "La célèbre photo du passage piéton a été prise en une dizaine de minutes."),
 ([POP], 'Musique', 'Le concert géant Live Aid, à Londres et Philadelphie', 1985, 3, "Phil Collins a joué sur les deux continents le même jour, grâce au Concorde."),
 ([POP], 'Musique', "La sortie de « Smells Like Teen Spirit » de Nirvana", 1991, 3, "Le titre vient d'une marque de déodorant."),
 ([POP], 'Cinéma', "La sortie de « Astérix et Obélix contre César », avec Gérard Depardieu", 1999, 3, "Christian Clavier y joue Astérix."),
 ([POP], 'Livres', 'La première publication du « Petit Prince » de Saint-Exupéry', 1943, 3, "Il a d'abord été publié aux États-Unis, en anglais et en français."),
 ([POP, HS], 'Livres', "La publication des « Misérables » de Victor Hugo", 1862, 3, "Hugo l'a terminé en exil, sur l'île de Guernesey."),
 ([POP, HS], 'Musique', 'La naissance de Mozart', 1756, 3, "Il composait déjà de petites pièces à cinq ans."),
 ([POP, HS], 'Technologie', 'La présentation du premier iPod', 2001, 3, "Steve Jobs le présentait comme « 1 000 chansons dans votre poche »."),
 # ── Histoire & sciences ──────────────────────────────────
 ([HS], 'Médecine', 'La première greffe du cœur, par Christiaan Barnard', 1967, 3, "L'opération a eu lieu au Cap, en Afrique du Sud."),
 ([HS], 'Sciences', "La découverte de la structure en double hélice de l'ADN", 1953, 3, "Les travaux de la chercheuse Rosalind Franklin ont été décisifs."),
 ([HS, G], 'Espace', 'Le premier vol habité dans l’espace, par Youri Gagarine', 1961, 2, "Son vol autour de la Terre a duré 108 minutes."),
 ([HS, G], 'Histoire', "L'accident de la centrale nucléaire de Tchernobyl", 1986, 1, "La ville voisine de Pripiat est restée abandonnée depuis."),
 ([HS], 'Sciences', 'La publication de la relativité restreinte par Albert Einstein', 1905, 3, "Il travaillait alors dans un bureau des brevets, à Berne."),
 ([HS], 'Sciences', 'La découverte de la radioactivité par Henri Becquerel', 1896, 3, "Il l'a découverte grâce à des plaques photographiques rangées avec des sels d'uranium."),
 ([HS], 'Médecine', 'La première vaccination contre la rage, par Louis Pasteur', 1885, 3, "Le premier patient, Joseph Meister, avait neuf ans."),
 ([HS, G], 'Histoire', 'Le sacre de Napoléon Ier, à Notre-Dame de Paris', 1804, 2, "Il s'est couronné lui-même, en présence du pape."),
 ([HS], 'Histoire', "La bataille d'Hastings", 1066, 3, "La tapisserie de Bayeux, longue de près de 70 mètres, raconte cette bataille."),
 ([HS], 'Histoire', "L'abolition définitive de l'esclavage dans les colonies françaises", 1848, 3, "Le décret a été porté par Victor Schœlcher."),
 ([HS, G], 'Société', 'L’ordonnance qui donne le droit de vote aux femmes en France', 1944, 2, "Elles ont voté pour la première fois l'année suivante, aux élections municipales."),
 ([HS, G], 'Histoire', 'Le début de la Première Guerre mondiale', 1914, 1, "Elle a été déclenchée après l'assassinat de l'archiduc François-Ferdinand à Sarajevo."),
 ([HS], 'Histoire', 'La mort de Jeanne d’Arc, à Rouen', 1431, 3, "Elle avait environ 19 ans."),
 ([HS], 'Histoire', "La révolution d'Octobre, en Russie", 1917, 2, "Elle a eu lieu en novembre selon notre calendrier : la Russie utilisait encore l'ancien."),
 ([HS], 'Internet', 'L’invention du Web par Tim Berners-Lee, au CERN', 1989, 3, "Le CERN se trouve à cheval sur la frontière entre la France et la Suisse."),
 ([HS], 'Inventions', 'Le premier vol en montgolfière avec des passagers humains', 1783, 3, "Avant les humains, un mouton, un canard et un coq avaient fait le voyage."),
 ([HS], 'Espace', 'La toute première image d’un trou noir rendue publique', 2019, 3, "Ce trou noir se trouve au cœur d'une galaxie située à environ 55 millions d'années-lumière."),
 ([HS], 'Espace', 'Le lancement de Spoutnik, premier satellite artificiel', 1957, 2, "Il émettait un simple « bip-bip » que des radioamateurs du monde entier pouvaient capter."),
 ([HS, G], 'Histoire', "L'élection de Nelson Mandela à la présidence de l'Afrique du Sud", 1994, 2, "Il avait passé 27 ans en prison avant d'être libéré."),
 ([HS], 'Espace', 'La mission Apollo 13', 1970, 3, "La phrase « Houston, on a eu un problème » vient de cette mission."),
 ([HS], 'Espace', "L'arrivée du robot Curiosity sur Mars", 2012, 3, "Il fonctionne grâce à une source d'énergie nucléaire, et non avec des panneaux solaires."),
 ([HS], 'Espace', 'Le tout premier lancement de la fusée Ariane', 1979, 3, "Elle a décollé de Kourou, en Guyane."),
 ([HS], 'Espace', 'La découverte de Pluton', 1930, 3, "Pluton a été rétrogradée au rang de planète naine en 2006."),
 ([HS], 'Société', 'La loi de séparation des Églises et de l’État en France', 1905, 3, "Elle garantit la liberté de conscience et le libre exercice des cultes."),
 ([HS, POP], 'Technologie', 'L’envoi du tout premier SMS', 1992, 3, "Il disait simplement « Merry Christmas »."),
 ([HS, GEO], 'Archéologie', 'La découverte de la tombe de Toutânkhamon', 1922, 2, "Le jeune pharaon n'avait qu'environ 19 ans à sa mort."),
 ([HS], 'Archéologie', 'La découverte de la grotte de Lascaux', 1940, 3, "Elle a été découverte par quatre adolescents, partis à la recherche d'un chien selon la légende."),
 ([HS], 'Société', 'La création de la Croix-Rouge', 1863, 3, "Son fondateur, le Suisse Henry Dunant, a reçu le tout premier prix Nobel de la paix."),
 ([HS], 'Sciences', 'La remise des tout premiers prix Nobel', 1901, 3, "Alfred Nobel, qui les a créés, avait fait fortune grâce à la dynamite."),
 ([HS, G], 'Monuments', "L'incendie de Notre-Dame de Paris", 2019, 1, "La flèche qui s'est effondrée avait été dessinée au XIXe siècle par Viollet-le-Duc."),
 ([HS, POP], 'Art', 'Le vol de « La Joconde » au Louvre', 1911, 3, "Le voleur, un vitrier italien, l'a gardée deux ans chez lui."),
 ([HS], 'Histoire', 'La mort de Louis XIV', 1715, 3, "Il a régné 72 ans, un record pour un monarque européen."),
 # ── Compléments ──────────────────────────────────────────
 ([FOOD, HS], 'Sciences', 'Le brevet de Pasteur sur la conservation des vins par chauffage', 1865, 3, "Le procédé, appliqué ensuite au lait, porte aujourd'hui son nom : la pasteurisation."),
 ([FOOD, HS], 'Inventions', 'Le brevet anglais de la boîte de conserve en métal', 1810, 3, "L'ouvre-boîte n'a été inventé qu'une cinquantaine d'années plus tard."),
 ([POP, G], 'Fêtes', 'La toute première Fête de la musique', 1982, 2, "Elle a été lancée par le ministère de la Culture, alors dirigé par Jack Lang."),
 ([FOOD], 'Chocolat', 'La création de la marque de chocolat Milka', 1901, 3, "Son nom vient de « Milch » et « Kakao », lait et cacao en allemand."),
 ([FOOD], 'Bières', 'La signature du bail de la brasserie Guinness, à Dublin', 1759, 3, "Arthur Guinness a signé un bail de… 9 000 ans."),
 ([FOOD, HS, SC], 'Médecine', "L'expérience de James Lind montrant que les agrumes guérissent le scorbut", 1747, 3, "Ce médecin écossais a testé plusieurs remèdes sur des marins malades : seuls les agrumes ont marché."),
 ([FOOD, BE], 'Bières', 'Le premier brassin de la Stella Artois, préparée pour Noël', 1926, 3, "« Stella » veut dire « étoile » en latin, un clin d'œil à l'étoile de Noël."),
 ([FOOD], 'Cuisine', "La publication du « Guide culinaire » d'Auguste Escoffier", 1903, 3, "Il reste une référence pour les cuisiniers du monde entier."),
 ([G, POP], 'Jeux', "L'invention du Rubik's Cube", 1974, 2, "Son inventeur, un professeur hongrois, a mis environ un mois à résoudre son propre casse-tête."),
 ([G, HS], 'Société', "L'abolition de la peine de mort en France", 1981, 2, "La loi a été portée par le garde des Sceaux Robert Badinter."),
 ([G, HS], 'Société', "L'abaissement de l'âge de la majorité à 18 ans en France", 1974, 3, "Avant cette loi, on devenait majeur à 21 ans."),
]
